#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Superdryno
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdrystore.no/dame/chinos"
      direct_url URL      

    end  
end
