#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Predatornutrition
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.predatornutrition.com/en/armour-v-180-caps/"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :value => "Add to basket")
      
    end  
end
