#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Predatornutrition
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.predatornutrition.com/en/checkout/cart/"
      direct_url URL
      
      button(:basket_checkout, :class => "button button-large place-order btn-proceed-checkout btn-checkout")
      
       
      
      def remove_product_links
        link_elements(:class => "btn-remove btn-remove2 remove-item")
      end 
      
    end  
end
