#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Predatornutrition
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.predatornutrition.com/en/product/amino-acids/"
      direct_url URL      

    end  
end
