#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Predatornutrition
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.predatornutrition.com/en/onestepcheckout/"
		direct_url URL    
    end  
end
