#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Jaeger
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.jaeger.co.uk/women-jackets/women-jackets,en_GB,sc.html"
      direct_url URL      

    end  
end
