#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Jaeger
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.jaeger.co.uk/on/demandware.store/Sites-JGRUK-Site/en_GB/Default-Start"
      direct_url URL
      
  	  text_field(:username, :id=>"dwfrm_login_username")
      text_field(:password, :id=>"dwfrm_login_password")  
  	  button(:login_submit, :id => "submit")           
    end  
end
