#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Jaeger
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.jaeger.co.uk/Billfold%20Wallet/320024G,en_GB,pd.html?dwvar_320024G_color=07500&dwvar_320024G_size=ITM&start=34&cgid=men-accessories"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "addtobag")
      
    end  
end
