#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Superdryfi
	class ProductPage
		include PageObject
		include PeeriusHelper
		# site elements
		 
		
		# page elements
		
		button(:add_to_basket, :src=> "http://www.superdry.fi/public/images/languages/fi-FI/product/add-to-bag.png")
		



	end  
end
