#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Missselfridgede
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.missselfridge.de/de/msde/kategorie/kleidung-835163/kleider-835176"
      direct_url URL      

    end  
end
