#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Missselfridgede
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.missselfridge.de/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-3&storeId=13066&catalogId=34074&beginIndex=1&viewAllFlag=false&pageSize=40&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dress&x=0&y=0"
      direct_url URL            
    end  
end
