#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Missselfridgede
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.missselfridge.de/de/msde/produkt/kleidung-835163/kleider-835176/midikleid-mit-perlenstickerei-im-aztekenmuster-2097701?bi=1&ps=40"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id => "btn_add_2_shop_cart")
      
    end  
end
