#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Drmartensus
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.dmusastore.com/ShoppingCart.aspx"
      direct_url URL
      
      button(:basket_checkout, :id=>"btnCheckOutNowBottom")
      
       
      
      def remove_product_links
        button_elements(:name=>"bt_Delete")
      end 
      
    end  
end
