#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Drmartensus
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.dmusastore.com/p-5089-cyprus.aspx"
      direct_url URL
	  # site elements
       
      # page elements
      
      link(:add_to_basket, :text => "Add to Basket")
      
    end  
end
