#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Drmartensus
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.dmusastore.com/c-11-shoes.aspx"
      direct_url URL      

    end  
end
