#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Tommyhilfigeruk
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://uk.tommy.com/Tanks-Watch/1MJ1781348,en_GB,pd.html?cgid=114080#!color%3D000%26i%3D21%26size%3DOS"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :class=> "button active addtocartbutton greenbutton a  ")
       
      # page elements
      
      button(:add_to_basket, :class=> "button active addtocartbutton greenbutton a  ")
      
    end  
end
