#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topshopmy
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://my.topshop.com/en/tsmy/product/clothing-1157134/dresses-1157274/limited-edition-ruche-maxi-dress-2143001?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
