#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Wallisus
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wallisfashion.com/en/wlus/product/clothing-1004840/dresses-1004858/red-and-blue-leaf-print-dress-2119126?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
