#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topmansandpit
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://tm.sandpit.arcadiagroup.ltd.uk/webapp/wcs/stores/servlet/CatalogSearchResultCmd?langId=-1&storeId=12555&catalogId=33056&beginIndex=1&viewAllFlag=false&pageSize=20&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=xwef&x=0&y=0"
      direct_url URL            
    end  
end
