#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Walliseu
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://euro.wallisfashion.com/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-1&storeId=13075&catalogId=34092&beginIndex=1&viewAllFlag=false&pageSize=20&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dvd&x=53&y=15"
      direct_url URL            
    end  
end
