#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Walliseu
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://euro.wallisfashion.com/en/wleu/product/clothing-989288/dresses-989306/black-mesh-detail-dress-2079938?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
