#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Thewhitecompany
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.thewhitecompany.com/login.aspx"
      direct_url URL
      
  	  text_field(:username, :id=>"in_txtEmailAddress")
      text_field(:password, :id=>"in_txtPassword")  
  	  button(:login_submit, :id=>"in_bLogin")           
    end  
end
