#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
module Thewhitecompany
  
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.thewhitecompany.com/"
      direct_url URL
      
      link(:login_link, :link => "Sign in . register")
	    text_field(:search, :id => "in_site_search")
    end  
end