#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Thewhitecompany
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.thewhitecompany.com/clothing/tops/"
      direct_url URL      

    end  
end
