#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Fatface
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.fatface.com/dresses/lilah-border-dress/invt/40989/?colour=Navy"
      direct_url URL
      
      button(:add_to_basket, :id=> "addproduct")          
    end  
end