#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Fatface
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.fatface.com/women/dresses/icat/womensdresses/"
      direct_url URL            
    end  
end