#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Fatface
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.fatface.com/bin/venda?ex=co_wizr-shopcart&bsref=fatface&log=22"
      direct_url URL
      
      button(:basket_checkout, :class => "button buttonArrow right btCheckout submit")            
    end  
end