#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Superdrydk
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.dk/search/jacket"
      direct_url URL            
    end  
end
