#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Brora
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = ""
		direct_url URL    
    end  
end
