#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Brora
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.brora.co.uk/CheckOut/Login.aspx"
      direct_url URL
      
  	  text_field(:username, :id=>"ctl00_BrowseContentPlaceHolder_EmailAddressTextBox")
      text_field(:password, :id=>"ctl00_BrowseContentPlaceHolder_PasswordTextBox")  
  	  button(:login_submit, :name=>"ctl00_BrowseContentPlaceHolder_ExistingCustomerLoginButton")           
    end  
end
