#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Brora
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.brora.co.uk/Product/Category.aspx?WebShopCodeStr=S4&WebSegmentCodeStr=S5&WebCategoryCodeStr=CS"
      direct_url URL      

    end  
end
