#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Bhs
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.bhs.co.uk/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-1&storeId=13077&catalogId=34096&beginIndex=1&viewAllFlag=false&pageSize=40&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dress"
      direct_url URL            
    end  
end