#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Bhs
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.bhs.co.uk/webapp/wcs/stores/servlet/LogonForm?catalogId=34096&storeId=13077&krypto=bw2BpuZQvDKkxtoRhWgVLg%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  button(:login_submit, :id=>"login_submit")           
    end  
end

