#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Bhs
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.bhs.co.uk/webapp/wcs/stores/servlet/ProductDisplay?beginIndex=1&viewAllFlag=&catalogId=34096&storeId=13077&productId=8720953&langId=-1&sort_field=Relevance&categoryId=471259&parent_categoryId=471112&pageSize=40"
      direct_url URL
      
      button(:add_to_basket, :id=> "ctl00_ctl00_globalmaincontent_productcontent_btnHiddenAddToBasketRef")          
    end  
end