#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
module Bakerross
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.bakerross.co.uk/"
      direct_url URL
      
      link(:login_link, :class => "small-whtext")
	    text_field(:search, :id => "searchINPUT")
    end  
end