#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Bakerross
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.bakerross.co.uk/category-Glues-and-Adhesives-ARTSGLUE.htm"
      direct_url URL            
    end  
end