#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Bakerross
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.bakerross.co.uk/customer_lookup.asp"
      direct_url URL
      
  	  text_field(:username, :id=>"emaillogin")
      text_field(:password, :id=>"passwordOnSignIn")  
  	  link(:login_submit, :href => "javascript:submit_login();")           
    end  
end

