#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Toast
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.toast.co.uk/search/keywords+are+top/top.htm"
      direct_url URL            
    end  
end
