#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Toast
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.toast.co.uk/category/dresses+and+tunics/dresses+tunics.htm"
      direct_url URL      

    end  
end
