#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Dorothyperkinssg
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://sg.dorothyperkins.com/en/dpsg/product/clothing-1491215/dresses-1491436/petite-diamante-2in1-dress-2132862?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
