#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Dorothyperkinssg
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://sg.dorothyperkins.com/en/dpsg/category/clothing-1491215/dresses-1491436"
      direct_url URL      

    end  
end
