#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Cooksongold
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.cooksongold.com/Solders/"
      direct_url URL      

    end  
end
