#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Cooksongold
	class ProductPage
		include PageObject
		include PeeriusHelper
		# site elements
		 
		
		# page elements
		
		link(:add_to_basket, :link_text => "Add to Basket")
		



	end  
end
