#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Wickes
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wickes.co.uk/tiles+floors/icat/tilesflooring/"
      direct_url URL      

    end  
end
