#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Wickes
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://search.wickes.co.uk/search#ts=ajax&method=and&w=bla&isort=score"
      direct_url URL            
    end  
end
