#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Wickes
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wickes.co.uk/tools-electrical+plumbing/icat/toolsstorage/"
      direct_url URL            
    end  
end