#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4
#

module Wickes
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wickes.co.uk/"
      direct_url URL
      
      link(:login_link, :title => "Login")
	  text_field(:search, :id => "sli_search_1")
    end  
end