#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Wickes
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wickes.co.uk/rimini-round-basin-500mm+full-pedestal/invt/220725/"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :class=> "bt_prodtail")
      
    end  
end
