#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4
#

module Wickes
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.wickes.co.uk/webapp/wcs/stores/servlet/LogonForm?catalogId=33057&storeId=12556&krypto=bw2BpuZQvDKkxtoRhWgVLg%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end

