#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Wickes
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wickes.co.uk/bin/venda?ex=co_wizr-shopcart&bsref=wickes&log=22"
      direct_url URL
      
      button(:basket_checkout, :id => "ctl00_contentBody_submit")            
    end  
end