#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4
#

module Wickes
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wickes.co.uk/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?catalogId=33057&storeId=12556&langId=-1&viewAllFlag=false&sort_field=Relevance&categoryId=208523&parent_categoryId=203984&beginIndex=1&pageSize=20&intcmpid=W_SUPERCAT_LEFTNAV_CLOTHING_UK_WK1_DRESSES"
      direct_url URL            
    end  
end