#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4 on 2013-02-05 15:01:50 +0000
#

module Wickes
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wickes.co.uk/"
      direct_url URL
      
      link(:login_link, :title => "Login")            
    end  
end