#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Superdrycacaen
	class ProductPage
		include PageObject
		include PeeriusHelper
		# site elements
		 
		
		# page elements
		
		button(:add_to_basket, :src=> "http://www.superdrystore.ca/ca-en/public/images/languages/en-GB/product/add-to-bag.png")
		



	end  
end
