#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4
#

module Topman
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.topman.com/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-1&storeId=12556&catalogId=33057&beginIndex=1&viewAllFlag=false&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dvd&x=0&y=0"
      direct_url URL            
    end  
end