#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Topman
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.topman.com/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-1&storeId=12555&catalogId=33056&beginIndex=1&viewAllFlag=false&pageSize=20&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=hsdg&x=0&y=0"
      direct_url URL            
    end  
end