#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Topman
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.topman.com/webapp/wcs/stores/servlet/ProductDisplay?beginIndex=1&viewAllFlag=&catalogId=33056&storeId=12555&productId=8997440&langId=-1&sort_field=Relevance&categoryId=207300&parent_categoryId=207298&pageSize=20"
      direct_url URL
      
      button(:add_to_basket, :class=> "btn_add_2_shop_cart")          
    end  
end