#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topman
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.topman.com/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?catalogId=33056&storeId=12555&langId=-1&viewAllFlag=false&sort_field=Relevance&categoryId=207183&parent_categoryId=207169&beginIndex=1&pageSize=20"
      direct_url URL      

    end  
end
