#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Topman
    class CheckoutPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.topman.com/webapp/wcs/stores/servlet/OrderDisplay?langId=-1&catalogId=33056&storeId=12555&krypto=8F4rqMW1NIT2HrCzbTrqrqDR7yDlD1DPQ615%2FcCIvMFAtaBWSUJQ3orUXX0vDr8yynd7e5Em9po%2B%0Ab6G3FEJEzOaR93mGfy912FhaKRztz2NN9D5wzBx5ec2HWvPkFeLnmkMaee9jFu%2BvsylsnWfiP6q5%0AvW5CtGjzmbAf50K2rpCMIe1kbbGeSvrSav7sMoOxw824C%2FjYz3DoB844hs4fefI%2ByCJOs7lxDZRy%0AytXBve05uUXzhts8SgiRk9wSD5%2BhTnJAfC3Q9yQ1n5ZzzJum%2FKmA0JtJM%2FmHB0%2FKcOmj3lQ1lCmt%0ABOLHQukEAyU6GMRT%2BZMfVSm2ZT6aTHXis%2F3G6eel9L3bjwJI6v%2BQBLM0aObRZbCt55kMV%2Fppx3gD%0AYNaF8vx49ccwh1g%3D&ddkey=http:CatalogNavigationSearchResultCmd"
      direct_url URL            
    end  
end