#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#
module Demostore
  
    class OrderPage
      include PageObject
      include PeeriusHelper
      
      URL = ""
      direct_url URL            
    end  
end
