#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Demostore
	class CategoryPage
		include PageObject
		include PeeriusHelper

		
		ul(:category_menu, :id => "nav")
		
	end  
end
