#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Demostore
	class ProductPage
		include PageObject
		include PeeriusHelper
		# site elements
		
		button(:add_to_basket, :xpath=> "//form[@id=\"product_addtocart_form\"]/div/div/div/button")
		 
		
		div(:product_links, :xpath=> "html/body/div[1]/div/div/div[2]/div/div[2]/div[2]")
		
		# page elements
		



	end  
end
