#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Demostore
  
    class HomePage
		include PageObject
		include PeeriusHelper

		URL = "http://showcase.peerius.com/index.php"
		direct_url URL
		# site elements
		
		ul(:category_menu, :id => "nav")
		
		
		div(:product_links, :xpath=> "html/body/div[1]/div/div/div[2]/div/div[2]/div[2]")
		
      
    end  
end
