#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Demostore
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://showcase.peerius.com/index.php/catalogsearch/result/?q=dvd"
      direct_url URL            
    end  
end
