#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Beautyexpert
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.beautyexpert.co.uk/health-beauty/skincare/night-treatments.list"
      direct_url URL            
    end  
end