#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Beautyexpert
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.beautyexpert.co.uk/decleor-travel-essentials-for-sensitive-skin-5-products/10616195.html"
      direct_url URL
      
      link(:add_to_basket, :class=> "productbuy")          
    end  
end