#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Missselfridgeus
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://us.missselfridge.com/en/msus/product/apparel-893014/dresses-893027/aztec-beaded-midi-dress-2088038?bi=1&ps=40"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id => "btn_add_2_shop_cart")
      
    end  
end
