#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Missselfridgeus
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://us.missselfridge.com/webapp/wcs/stores/servlet/LogonForm?catalogId=34080&storeId=13069&krypto=bw2BpuZQvDKkxtoRhWgVLg%3D%3D&ddkey=http:CatalogNavigationSearchResultCmd"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
