#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Greatplains
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.greatplains.co.uk/checkout.htm"
		direct_url URL    
    end  
end
