#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Greatplains
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.greatplains.co.uk/product/womens+Accessories/JGAMB/Amelie+Chunky+Knit+Night+Socks.htm"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id => "addToBasket")
      
    end  
end
