#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Wolfordus
	class ProductPage
		include PageObject
		include PeeriusHelper
		# site elements
		 
		
		# page elements
		
		a(:add_to_basket, :id => "add-to-cart-button-id")
		



	end  
end
