#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Wheelies
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.wheelies.co.uk/Checkout.aspx"
		direct_url URL    
    end  
end
