#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Wheelies
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wheelies.co.uk/ViewCart.aspx"
      direct_url URL
      
       
      
    end  
end
