#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
module Schuh
  
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.schuh.co.uk/"
      direct_url URL
      
      link(:login_link, :id => "ctl00_lnkMyAccount")
	    text_field(:search, :id => "searchBox")
    end  
end