#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Schuh
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www1.schuh.co.uk/basket.aspx"
      direct_url URL
      
      link(:basket_checkout, :href => "https://secure1.schuh.co.uk/chklogin.aspx")            
    end  
end