#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Ccfashion
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.ccfashion.co.uk/pws/secure/CheckoutAddressAction.ice"
		direct_url URL    
    end  
end
