#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Ccfashion
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.ccfashion.co.uk/fcp/categorylist/dept/dresses"
      direct_url URL      

    end  
end
