#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Ccfashion
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.ccfashion.co.uk/pws/CatalogueSearch.ice?layout=searchresults.layout&performSearch=true&visible=true&productAttributeName=&productAttributeValue=&productsPerPage=9999&resetFilters=true&isServiceProduct=false&keywords=dress&x=0&y=0"
      direct_url URL            
    end  
end
