#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %>
#

<% page = site["product_page"] %>
module <%= site["site_name"].capitalize %>
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "<%= page["URL"] %>"
      direct_url URL
      
      <%= page["add_to_basket_button"][0] %>(:add_to_basket, <%= page["add_to_basket_button"][1] %>)          
    end  
end