#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %>
#

module <%= site["site_name"].capitalize %>
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "<%= site["product_page"]["URL"] %>"
      direct_url URL
      
      <%= site["product_page"]["add_to_basket_button"][0] %>(:add_to_basket, <%= site["product_page"]["add_to_basket_button"][1] %>)          
    end  
end