#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %> on <%= Time.now %>
#

module <%= site["site_name"].capitalize %>
    class CheckoutPage
      include PageObject
      include PeeriusHelper
      
      URL = "<%= site["checkout_page"]["URL"] %>"
      direct_url URL            
    end  
end