#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %>
#

module <%= site["site_name"].capitalize %>
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "<%= site["login_page"]["URL"] %>"
      direct_url URL
      
  	  text_field(:username, <%= site["login_page"]["username_field"] %>)
      text_field(:password,<%= site["login_page"]["password_field"] %>)  
  	  <%= site["login_page"]["login_submit"][0] %>(:login_submit, <%= site["login_page"]["login_submit"][1] %>)           
    end  
end

