<% if site["ignore"] or site["ignore_web"]%>
#ignore
<% end %>
#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %>
#

<% if site["product_page"] %>
<% page = site["product_page"] %>
module <%= site["site_name"].capitalize %>
	class ProductPage
		include PageObject
		include PeeriusHelper
		# site elements
		<% if site["add_to_basket_button"] %>
		<%= site["add_to_basket_button"][0] %>(:add_to_basket, <%= site["add_to_basket_button"][1] %>)
		<% end %> 
		<% if site["product_links"] %>
		<%= site["product_links"][0] %>(:product_links, <%= site["product_links"][1] %>)
		<% end %>
		# page elements
		<% if page["add_to_basket_button"] %>
		<%= page["add_to_basket_button"][0] %>(:add_to_basket, <%= page["add_to_basket_button"][1] %>)
		<% end %>



	end  
end
<% end %>