#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %>
#

module <%= site["site_name"].capitalize %>
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "<%= site["category_page"]["URL"] %>"
      direct_url URL            
    end  
end