<% if site["ignore"] or site["ignore_web"]%>
#ignore
<% end %>
#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %>
#

<% if site["product_page"] %>
<% page = site["product_page"] %>
module <%= site["site_name"].capitalize %>
	class ProductPage
		include PageObject
		include PeeriusHelper

		<%= page["add_to_basket_button"][0] %>(:add_to_basket, <%= page["add_to_basket_button"][1] %>) 

		<% if page["product_links"] %>
		<%= page["product_links"][0] %>(:product_links, <%= page["product_links"][1] %>)
		<% end %>
	end  
end
<% end %>