#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %>
#

<% page = site["searchresults_page"] %>
module <%= site["site_name"].capitalize %>
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "<%= page["URL"] %>"
      direct_url URL            
    end  
end