<% if site["ignore"] or site["ignore_web"]%>
#ignore
<% end %>
#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %>
#

<% if site["home_page"] %>
<% page = site["home_page"] %>
module <%= site["site_name"].capitalize %>
  
    class HomePage
		include PageObject
		include PeeriusHelper

		URL = "<%= debug_url(page["URL"]) %>"
		direct_url URL
        <%= page["search_field"][0] %>(:search, <%= page["search_field"][1] %>)
        # site elements
		<% if site["category_menu"] %>
		<%= site["category_menu"][0] %>(:category_menu, <%= site["category_menu"][1] %>)
		<% end %>
		<% if site["product_links"] %>
		<%= site["product_links"][0] %>(:product_links, <%= site["product_links"][1] %>)
		<% end %>
		#page elements - retained for backward compatibility
		<% if page["login_link"] %>
		<%= page["login_link"][0] %>(:login_link, <%= page["login_link"][1] %>)
		<% end %>
		<% if page["category_menu"] %>
		<%= page["category_menu"][0] %>(:category_menu, <%= page["category_menu"][1] %>)
		<% end %>
		
		<% if site["max_num_of_categories"] %>
		def get_max_num_of_categories
		        return <%= site["max_num_of_categories"] %>
        end 
        <% end %>
      
    end  
end
<% end %>