<% if site["ignore"] or site["ignore_web"]%>
#ignore
<% end %>
#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %>
#

<% if site["basket_page"] %>
<% page = site["basket_page"] %>
module <%= site["site_name"].capitalize %>
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "<%= debug_url(page["URL"]) %>"
      direct_url URL
      
      <%= page["basket_checkout"][0] %>(:basket_checkout, <%= page["basket_checkout"][1] %>)
    
      def remove_product_links
        <%= page["basket_remove"][0] %>_elements(<%= page["basket_remove"][1] %>)
      end   
    end  
end
<% end %>