#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %> on <%= Time.now %>
#

module <%= site["site_name"].capitalize %>
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "<%= site["product_page"]["URL"] %>"
      direct_url URL
      
      button(:add_to_basket, <%= site["product_page"]["add_to_basket_button"] %>)
      select_list(:size_select, :class => "product_size_full")
      link(:size_link, :class => "active")            
    end  
end