#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Superdrynl
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.superdry.nl/checkout"
		direct_url URL    
    end  
end
