#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Burtoneu
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://eu.burton-menswear.com/en/breu/category/clothing-1676695/mens-jeans-1676801"
      direct_url URL      

    end  
end
