#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Burtoneu
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://eu.burton-menswear.com/webapp/wcs/stores/servlet/OrderItemDisplay?catalogId=35119&langId=-1&storeId=13091"
      direct_url URL
      
      link(:basket_checkout, :title => "Checkout")
      
       
      
      def remove_product_links
        link_elements(:class => "remove_bag_item")
      end 
      
    end  
end
