#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Royalmint
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.royalmint.com/security/login"
      direct_url URL
      
  	  text_field(:username, :id=>"maincontent_0_ctl01_txtEmail")
      text_field(:password, :id=>"maincontent_0_ctl01_txtPassword")  
  	  button(:login_submit, :id=>"maincontent_0_ctl01_btnLogin")           
    end  
end
