#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Royalmint
	class ProductPage
		include PageObject
		include PeeriusHelper
		# site elements
		
		button(:add_to_basket, :id=> "maincontent_0_add_btnAddToCart")
		 
		
		div(:product_links, :xpath=> "#shop-item-container/div/div/a[0]")
		
		# page elements
		



	end  
end
