#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Royalmint
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.royalmint.com/shop/lunar_year_of_the_horse_2014_uk_one_ounce_silver_proof_coin"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :id=> "maincontent_0_add_btnAddToCart")
       
      # page elements
      
    end  
end
