#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Tommyhilfigereu
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://eu.tommy.com/Pauma-Fitted-Rugby-Sweatshirt/1M87633532,default,pd.html?cgid=106000#!color%3D322%26i%3D7"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :class=> "button active addtocartbutton a")
      
    end  
end
