#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Hqhair
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.hqhair.com/elysium.search?search=CREAM"
      direct_url URL            
    end  
end