#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Hqhair
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.hqhair.com/moroccanoil-the-original-oil-treatment-25ml/10448780.html"
      direct_url URL
      
      link(:add_to_basket, :class=> "productbuy")          
    end  
end