#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Hqhair
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.hqhair.com/health-beauty/skincare/anti-ageing.list"
      direct_url URL            
    end  
end