#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Lookfantastic
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://hairandbeauty.lookfantastic.com/search?asug=&w="
      direct_url URL            
    end  
end