#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Lookfantastic
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.lookfantastic.com/lookfantasticgroup/my.basket?mvtCTA=a"
      direct_url URL
      
      link(:basket_checkout, :class => "fr")            
    end  
end