#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Lookfantastic
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.lookfantastic.com/brands/ardell-lashes.list?mvtCTA=a"
      direct_url URL            
    end  
end