#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Lookfantastic
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.lookfantastic.com/md-formulations-facial-cleanser-all-skin-types-250ml/10548664.html"
      direct_url URL
      
      button(:add_to_basket, :id=> "cat-button buynow thg-track")          
    end  
end