#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Lookfantastic
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.lookfantastic.com/brands/ardell-lashes.list"
      direct_url URL            
    end  
end