#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
module Lookfantastic
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.lookfantastic.com/home.dept"
      direct_url URL
      
      link(:login_link, :link=> "Sign in")
	    text_field(:search, :id => "sli_search_1")
    end  
end