#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
module Lookfantastic
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.lookfantastic.com/home.dept"
      direct_url URL
      
      link(:login_link, :href=> "https://www.lookfantastic.com/lookfantasticgroup/login.jsp")
	    text_field(:search, :id => "search_term")
    end  
end