#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Superdry
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.com/search/jacket"
      direct_url URL            
    end  
end
