#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Superdry
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.com/womens/dresses"
      direct_url URL      

    end  
end
