#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topshopsg
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://sg.topshop.com/en/tssg/category/clothing-1087626/dresses-1087766"
      direct_url URL      

    end  
end
