#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topmansg
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://sg.topman.com/en/tmsg/category/shoes-and-accessories-1928533/boots-1365447"
      direct_url URL      

    end  
end
