#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topshopth
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://th.topshop.com/webapp/wcs/stores/servlet/LogonForm?catalogId=35115&storeId=13089&krypto=UWKqAc2Na6jZ%2FeIWylXDvdfGbkpklaHuqdWHfNoH9IblSSdEioHYfbZrXf7Ji%2BRU%2FwuBeJYccM9c%0A1K%2FiR2kXpA%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
