#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topshopth
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://th.topshop.com/en/tsth/category/clothing-1226642/dresses-1226782"
      direct_url URL      

    end  
end
