#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Tommyhilfigerfr
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://fr.tommy.com/Nanette-Top/1657628583,fr_FR,pd.html?cgid=408000"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :class=> "button active addtocartbutton a")
      
    end  
end
