#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
module Lovehoney
  
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.lovehoney.co.uk/"
      direct_url URL
      
      link(:login_link, :href=>"https://www.lovehoney.co.uk/your-account/")
	    text_field(:search, :id => "headerSearch")
    end  
end