#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Lovehoney
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://search.lovehoney.co.uk/"
      direct_url URL            
    end  
end