#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Topshopeu
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://eu.topshop.com/webapp/wcs/stores/servlet/ProductDisplay?beginIndex=1&viewAllFlag=&catalogId=34058&storeId=13058&productId=9493054&langId=-1&sort_field=Relevance&categoryId=339056&parent_categoryId=339500&pageSize=20"
      direct_url URL
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")          
    end  
end