#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topshopeu
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://eu.topshop.com/en/tseu/category/clothing-485092/dresses-485107"
      direct_url URL      

    end  
end
