#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
module Topshopeu
  
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "http://eu.topshop.com/webapp/wcs/stores/servlet/TopCategoriesDisplay?storeId=13058&catalogId=34058&geoip=home"
      direct_url URL
      
      link(:login_link, :title => "Sign in or register")
	    text_field(:search, :id => "inp_search_text")
    end  
end