#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Topshopeu
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://eu.topshop.com/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-1&storeId=13058&catalogId=34058&beginIndex=1&viewAllFlag=false&pageSize=20&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dvd&x=0&y=0"
      direct_url URL            
    end  
end