#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Mandco
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.mandco.com/bin/venda?ex=co_wizr-shopcart&display=1&stashid=billtologincaa759c&workflowid=shopcart_1&step=billtologin"
      direct_url URL
      
  	  text_field(:username, :id=>"email")
      text_field(:password, :id=>"password")  
  	  button(:login_submit, :class=>"button buttonAlt submit", :index => 1)           
    end  
end

