#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Mandco
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.mandco.com/search?q=asjkfhk&categoryPathRefs=10"
      direct_url URL            
    end  
end