#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Mandco
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.mandco.com/floral-stripe-dress/invt/1208489multi/&bklist=icat,5,10,10010,10010090,10010090190"
      direct_url URL
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")          
    end  
end