#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Mandco
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.mandco.com/bin/venda?ex=co_wizr-shopcart&bsref=mackays&log=22"
      direct_url URL
      
      link(:basket_checkout, :class => "btn_checkout")            
    end  
end