#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Mandco
    class CheckoutPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.mandco.com/bin/venda?ex=co_wizr-shopcart&bsref=mackays&wizard=shopcart&step=confirm&param1=login"
      direct_url URL            
    end  
end