#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Mandco
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.mandco.com/dresses-/new-dresses/icat/10010090190/"
      direct_url URL            
    end  
end