#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Dorothyperkinsde
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://de.dorothyperkins.com/de/dpde/kategorie/bekleidung-649134/kleider-649158"
      direct_url URL      

    end  
end
