#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Dorothyperkinsde
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://de.dorothyperkins.com/de/dpde/produkt/bekleidung-649134/kleider-649158/hautfarbenes-kleid-mit-gro%C3%9Fen-schmucksteinen-2073654?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
