#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Tommyhilfigerchde
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://ch.tommy.com/on/demandware.store/Sites-CH-Site/de_CH/Search-Show?q=shirt"
      direct_url URL            
    end  
end
