#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Tommyhilfigerchde
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://ch.tommy.com/Polos/206000,de_CH,sc.html"
      direct_url URL      

    end  
end
