#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Burton
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.burton.co.uk/webapp/wcs/stores/servlet/ProductDisplay?beginIndex=1&viewAllFlag=&catalogId=33052&storeId=12551&productId=8062853&langId=-1&sort_field=Relevance&categoryId=427002&parent_categoryId=223521&pageSize=20"
      direct_url URL
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")          
    end  
end