#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Burton
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.burton.co.uk/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?catalogId=33052&storeId=12551&langId=-1&viewAllFlag=false&sort_field=Relevance&categoryId=427002&parent_categoryId=223521&beginIndex=1&pageSize=20"
      direct_url URL            
    end  
end