#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
module Burton
  
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.burton.co.uk/webapp/wcs/stores/servlet/TopCategoriesDisplay?storeId=12551&catalogId=33052"
      direct_url URL
      
      link(:login_link, :link => "Sign in or register")
	    text_field(:search, :id => "inp_search_text")
    end  
end