#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Tommyhilfigerbefr
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://be.tommy.com/on/demandware.store/Sites-BE-Site/fr_BE/Search-Show?q=shirt"
      direct_url URL            
    end  
end
