#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Tommyhilfigerbefr
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://be.tommy.com/Tommy-Chemise-Polo-Coupe-%22slim%22/0857837577,fr_BE,pd.html?cgid=206000#!color%3D083%26i%3D2"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :class=> "button active addtocartbutton a")
      
    end  
end
