#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Missselfridgefr
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.missselfridge.fr/webapp/wcs/stores/servlet/LogonForm?catalogId=34076&storeId=13067&krypto=bw2BpuZQvDKkxtoRhWgVLg%3D%3D&ddkey=http:en/bhuk/category/for-the-home-1020589/"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id => "login_submit")           
    end  
end
