#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topmanth
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://sg.topman.com/webapp/wcs/stores/servlet/LogonForm?catalogId=35103&storeId=13083&krypto=vyjFCHiZmFiAnJ8jbihgtOfUU5jKBw1XsSDv0JlhjaWohFMkUrs6HYmo4r4kKT8suUhcoWXJ%2FrRM%0ARBE4cmcyuQ%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
