#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topmanth
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://th.topman.com/en/tmth/category/clothing-1428201/mens-jeans-1428267"
      direct_url URL      

    end  
end
