#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topmanth
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://th.topman.com/en/tmth/product/shoes-and-accessories-1928534/boots-1428193/clarks-original-black-desert-shoes-2130107?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
