#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Kickzde
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.kickz.com/de/checkout/addresses?actionName=addresses"
		direct_url URL    
    end  
end
