#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Simplypersonalized
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.simplypersonalized.com/Search.aspx?page=1&keywords=dad"
      direct_url URL            
    end  
end
