#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Drmartensuk
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://uk.drmartens.com/uk/cart"
      direct_url URL
      
      button(:basket_checkout, :id=>"checkoutButtonBottom")
      
       
      
      def remove_product_links
        link_elements(:href=>"javascript:submitRemove(0);")
      end 
      
    end  
end
