#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Drmartensuk
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://uk.drmartens.com/uk/Accessories/Accessories-Shoe-Care/Dr-Martens-Ultra-Protector/p/AC034001"
      direct_url URL
	  # site elements
      
      link(:add_to_basket, :id => "prod_add_to_cart_bt")
       
      # page elements
      
      link(:add_to_basket, :id => "prod_add_to_cart_bt")
      
    end  
end
