#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Drmartensuk
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://store.drmartens.co.uk/checkoutpayment.aspx"
		direct_url URL    
    end  
end
