#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Drmartensuk
	class ProductPage
		include PageObject
		include PeeriusHelper
		# site elements
		 
		
		# page elements
		
		link(:add_to_basket, :id => "prod_add_to_cart_bt")
		



	end  
end
