#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Drmartensuk
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://uk.drmartens.com/uk/login"
      direct_url URL
      
  	  text_field(:username, :id=>"j_username")
      text_field(:password, :id=>"j_password")  
  	  button(:login_submit, :class=>"form yellowButton")           
    end  
end
