#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Mandmdirect
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.mandmdirect.com/Secure/Account/SignIn?ReturnUrl=%2FSecure%2FCheckout%2FAccount"
      direct_url URL
      
  	  text_field(:username, :id=>"ctl00_ctl00_globalmaincontent_maincontent_txtLogonId")
      text_field(:password, :id=>"ctl00_ctl00_globalmaincontent_maincontent_txtPassword")  
  	  button(:login_submit, :id=>"ctl00_ctl00_globalmaincontent_maincontent_btnlogin2")           
    end  
end

