#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Mandmdirect
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.mandmdirect.com/01/details/PX102/Womens-Conversational-Print-Dress-Dark-Red"
      direct_url URL
      
      button(:add_to_basket, :id=> "ctl00_ctl00_globalmaincontent_productcontent_btnHiddenAddToBasketRef")          
    end  
end