#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Mandmdirect
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.mandmdirect.com/01/womens/dresses-and-skirts"
      direct_url URL            
    end  
end