#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Missselfridgeuk
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.missselfridge.com/en/msuk/category/clothing-299047/dresses-299060"
      direct_url URL      

    end  
end
