#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Superdryfr
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.fr/femme/chinos/details/39116/pantacourt-commodity"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :value => "Ajouter au panier")
      
    end  
end
