#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Notonthehighstreet
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.notonthehighstreet.com/checkout/your_order"
		direct_url URL    
    end  
end
