#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Notonthehighstreet
    class CheckoutPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.notonthehighstreet.com/session/new"
      direct_url URL            
    end  
end