#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Notonthehighstreet
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.notonthehighstreet.com/home-garden/shop-by-room/kitchen"
      direct_url URL            
    end  
end