#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Notonthehighstreet
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.notonthehighstreet.com/women/womens-jewellery/necklaces-pendants"
      direct_url URL      

    end  
end
