#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Notonthehighstreet
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.notonthehighstreet.com/search"
      direct_url URL            
    end  
end