#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Notonthehighstreet
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.notonthehighstreet.com/the3blondebears/product/personalised-definition-text-mug"
      direct_url URL
      
      button(:add_to_basket, :id=> "add_to_cart")          
    end  
end