#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Burtonsandpit
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://br.sandpit.arcadiagroup.ltd.uk/webapp/wcs/stores/servlet/LogonForm?catalogId=33052&storeId=12551&krypto=uv4XFNHYwVG4uTPXJsCkTA%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
