#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Burtonsandpit
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://br.sandpit.arcadiagroup.ltd.uk/en/bruk/category/clothing-281559/mens-chinos-281636?ps=20&intcmpid=clothingchino&viewAllFlag=false&bi=1&sort_field=Relevance"
      direct_url URL      

    end  
end
