#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topshopus
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://us.topshop.com/en/tsus/product/clothing-70483/dresses-70497/toile-print-babydoll-dress-2905789?bi=1&ps=200"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
