#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Topshopus
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://us.topshop.com/webapp/wcs/stores/servlet/OrderItemDisplay?catalogId=33060&langId=-1&storeId=13052"
      direct_url URL
      
      link(:basket_checkout, :class => "btn_checkout")            
    end  
end