#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Topshopus
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://us.topshop.com/webapp/wcs/stores/servlet/ProductDisplay?beginIndex=1&viewAllFlag=&catalogId=33060&storeId=13052&productId=9493150&langId=-1&sort_field=Relevance&categoryId=208638&parent_categoryId=208580&pageSize=20"
      direct_url URL
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")          
    end  
end