#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topshopus
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://us.topshop.com/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?catalogId=33060&storeId=13052&langId=-1&viewAllFlag=false&sort_field=Relevance&categoryId=208641&parent_categoryId=208580&beginIndex=1&pageSize=20"
      direct_url URL      

    end  
end
