#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Tommyhilfigerat
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://at.tommy.com/Polos/106000,de_AT,sc.html"
      direct_url URL      

    end  
end
