#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Tommyhilfigerat
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://at.tommy.com/Chiara-Slim-Fit-Polo/8718398301785,de_AT,pd.html#moredetails"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :title=> "In den Warenkorb")
      
    end  
end
