#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Topmanus
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://us.topman.com/webapp/wcs/stores/servlet/LogonForm?catalogId=33059&storeId=13051&ddkey=http:LogonForm&geoip=noship"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end

