#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
module Topmanus
  
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "http://us.topman.com/webapp/wcs/stores/servlet/TopCategoriesDisplay?storeId=13051&catalogId=33059&geoip=home"
      direct_url URL
      
      link(:login_link, :title => "Login")
	    text_field(:search, :id => "inp_search_text")
    end  
end