#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topmanus
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://us.topman.com/webapp/wcs/stores/servlet/OrderItemDisplay?catalogId=33059&langId=-1&storeId=13051&geoip=noship"
      direct_url URL
      
      link(:basket_checkout, :class => "btn_checkout")
      
       
      
      def remove_product_links
        link_elements(:class => "remove_bag_item")
      end 
      
    end  
end
