#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Dorothyperkins
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.dorothyperkins.com/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-1&storeId=12552&catalogId=33053&beginIndex=1&viewAllFlag=false&pageSize=20&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dvd&x=0&y=0"
      direct_url URL            
    end  
end
