#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Dorothyperkins
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.evans.co.uk/webapp/wcs/stores/servlet/LogonForm?catalogId=33054&storeId=12553&krypto=6JGpwJoTBogcXSkJp6JNC3Y%2F%2BXJQOxw63aLFYCRK0JMlzcGOIqmXzu3xVgyPmHM8o9JUq3nioyjH%0AwO0dbQ%2BB%2BA%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
