#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Dorothyperkins
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.dorothyperkins.com/en/dpuk/category/clothing-203535/dresses-203559"
      direct_url URL      

    end  
end
