#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Thehut
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://malegrooming.mankind.co.uk/search?w=cream&asug="
      direct_url URL            
    end  
end