#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topmaneu
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://eu.topman.com/en/tmeu/product/clothing-617800/mens-shirts-617813/white-long-sleeve-smart-shirt-631922?bi=1&ps=20"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
