#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Topmaneu
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://eu.topman.com/webapp/wcs/stores/servlet/OrderCalculate?langId=-1&storeId=13061&catalogId=34064&updatePrices=1&calculationUsageId=-1&calculationUsageId=-2&calculationUsageId=-7&orderId=.&URL=OrderItemDisplay"
      direct_url URL
      
      link(:basket_checkout, :class => "btn_checkout")            
    end  
end