#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Topmaneu
  
    class CheckoutPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://us.topman.com/webapp/wcs/stores/servlet/OrderDisplay?langId=-1&catalogId=33059&storeId=13051&krypto=8F4rqMW1NIT2HrCzbTrqrqDR7yDlD1DPQ615%2FcCIvMFAtaBWSUJQ3vu3Bv%2B8FEmXn5qsPN4MTb%2Bn%0A3xLBVGOxDIgpieVQ8bzSYzLIGzMMCg6xIYXWM7g%2BJU8McBBz9GriSM%2BxCCAn9U1YUmKsLBDhgT0D%0A0GhtpGPsI8410o9YXpj3AUY6QacOzb8YojkDuiat5IULUSuIr9%2B8HePWer01aII%2FTSP3Oa1jDX%2Fl%0AXPuHJTimNo4%2FcIQY959QrIOBwea4WrXsQASMguEb5YIyGatshE%2FI4Z7QQFEZUmJBKv1z%2BVddarI%2B%0AYOA6STmzFy5inU9IWu7JUspBqktHD7HCDGuk%2FXbAzTtwUHWOwpRpDhBWzUL0JcC6OZhZ9h8mE5EZ%0Aaj6KnwUc4un3bX8%3D&ddkey=https:PreCheckout"
      direct_url URL            
    end  
end