#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Topmaneu
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://eu.topman.com/webapp/wcs/stores/servlet/LogonForm?catalogId=34064&storeId=13061&geoip=home"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end

