#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Topmaneu
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://eu.topman.com/webapp/wcs/stores/servlet/ProductDisplay?beginIndex=1&viewAllFlag=&catalogId=34064&storeId=13061&productId=8741205&langId=-1&sort_field=Relevance&categoryId=336017&parent_categoryId=336013&pageSize=20"
      direct_url URL
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")          
    end  
end