#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Wallisde
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wallismode.de/de/wlde/produkt/bekleidung-958225/kleider-958243/verziertes-kleid-2078247?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
