#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Dorothyperkinsid
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://id.dorothyperkins.com/webapp/wcs/stores/servlet/LogonForm?catalogId=35101&storeId=13082&krypto=2pKu5StkGJW6oLa7qayWtUKSa5%2B9V3%2B0IH8E4GC4CDihW47xNLBH0UE%2FZN%2BvtLtQYtP%2FXSCFWSDS%0AOLjsKxafqw%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
