#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Wallisfr
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wallismode.fr/fr/wlfr/cat%C3%A9gorie/v%C3%AAtements-973744/robes-973762"
      direct_url URL      

    end  
end
