#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Wallisfr
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wallismode.fr/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-2&storeId=13074&catalogId=34090&beginIndex=1&viewAllFlag=false&pageSize=20&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dvd&x=0&y=0"
      direct_url URL            
    end  
end
