#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Chemistdirect
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.chemistdirect.co.uk/registration/pay_confirm.php"
		direct_url URL    
    end  
end
