#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Chemistdirect
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.chemistdirect.co.uk/registration/sign_in.php"
      direct_url URL
      
  	  text_field(:username, :id=>"username")
      text_field(:password, :id=>"password")  
  	  button(:login_submit, :name=>"submit")           
    end  
end
