#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Chemistdirect
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.chemistdirect.co.uk/embarrassing-conditions_2_1.html"
      direct_url URL      

    end  
end
