#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Chemistdirect
	class ProductPage
		include PageObject
		include PeeriusHelper
		# site elements
		 
		
		# page elements
		
		link(:add_to_basket, :class => "buy_now")
		



	end  
end
