#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Superdrybebefr
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.be/be-fr/search/jacket"
      direct_url URL            
    end  
end
