#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Virginwines
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.virginwines.co.uk/cart/sc_main.jsp"
      direct_url URL
      
      button(:basket_checkout, :class=> "button redtogreen basketcheckout pro1")
      
       
      
      def remove_product_links
        link_elements(:class => "remove")
      end 
      
    end  
end
