#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Virginwines
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.virginwines.co.uk/AST/wines/PRD~C05086/d%27Arcana-Pinot-Grigio-2011.jsp"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :class => "button redtogreen")
      
    end  
end
