#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Virginwines
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.virginwines.co.uk/index.jsp?bmForm=filtered_search&SEARCH_INPUT%3C%3EsearchFor=&SEARCH_INPUT%3C%3EATR_WineStyle=*&SEARCH_INPUT%3C%3EATR_WineType=*&SEARCH_INPUT%3C%3EATR_Country=*&SEARCH_INPUT%3C%3EATR_MedalWinner=*&SEARCH_INPUT%3C%3EATR_MedalWinner=*&SEARCH_INPUT%3C%3EpriceRange=&SEARCH_INPUT%3C%3Eethical=false&SEARCH_INPUT%3C%3Eethical=false&SEARCH_INPUT%3C%3EATR_WineCategory=Rose"
      direct_url URL      

    end  
end
