#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Virginwines
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.virginwines.co.uk/AST/wines/PRD~C06055/Beneficio-Cellar-Reserve-McLaren-Vale-Shiraz-2009.jsp"
      direct_url URL
      
      button(:add_to_basket, :value => "Add to Basket")          
    end  
end