#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
module Virginwines
  
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.virginwines.co.uk/"
      direct_url URL
      
      link(:login_link, :title=> "register")
	    text_field(:search, :id => "search")
    end  
end