base_url: localpt.peerius.com
headless: false
database0: ImplLocalDenorm0
database1: ImplLocalDenorm1
database2: ImplLocalDenorm2
database3: ImplLocalDenorm3
database4: ImplLocalDenorm4
database5: Mod2Denorm5
database6: Mod2Denorm6
database7: Mod2Denorm7
username: 3duser
password: 3d534rch
host: isopoda

