base_url: localpt.peerius.com
headless: false
database0: ImplDenorm0
database1: ImplDenorm1
database2: ImplDenorm2
database3: ImplDenorm3
database4: ImplDenorm4
database5: Mod2Denorm5
database6: Mod2Denorm6
database7: Mod2Denorm7
username: 3duser
password: 3d534rch
host: isopoda

