base_url: localpt.peerius.com
headless: false
database0: Mod1Denorm0
database1: Mod1Denorm1
database2: Mod1Denorm2
database3: Mod1Denorm3
database4: Mod1Denorm4
database5: Mod1Denorm5
database6: Mod1Denorm6
database7: Mod1Denorm7
username: 3duser
password: 3d534rch
host: isopoda

