base_url: qa2.lan
headless: false
proxy: utils.lan:9100
database0: qadenorm0
database1: qadenorm1
database2: qadenorm2
database3: qadenorm3
database4: qadenorm4
database5: qadenorm5
database6: qadenorm6
database7: qadenorm7
username: 3duser
password: 3d534rch
host: testdb

