#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Redletterdays
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.redletterdays.co.uk/Basket.aspx"
      direct_url URL
      
      button(:basket_checkout, :id => "ctl00_contentBody_submit")            
    end  
end