#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Redletterdays
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.redletterdays.co.uk/mens-suits/mens-business-suits?q=peerius|||||||||||||||"
      direct_url URL      

    end  
end
