#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Redletterdays
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.redletterdays.co.uk/mens-suits/mens-business-suits?q=peerius|||||||||||||||"
      direct_url URL            
    end  
end