#!/usr/bin/env ruby

require 'erb'
require 'pp'
require 'psych'
require 'trollop'
require 'fileutils'
require_relative "rules.rb"
require_relative "helpers.rb"

QA_GENERATE_VERSION = "2.10.20141022"


# Specify commandline options
opts = Trollop::options do
	version "qa_generate #{QA_GENERATE_VERSION} (c) 2014 Peerius Ltd"
	banner <<-EOS
qa_generate is a test creation tool which takes YAML input (see: yaml.org) and
generates .feature and page class files in order to test Peerius code on client sites.

Usage:
	   qa_generate [options]
# Clarifications
where [options] are:
	EOS
	opt :sites_yaml_folder, "Sites YAML directory", :type => :string, :default => "sites"
	opt :templates, "Template directory", :type => :string, :default => "templates"
	opt :outfile, "Output directory", :type => :string, :default => "../../"
	opt :sites_alias_folder, "Sites alias directory", :type => :string, :default => "sites"
end

# Use an appropriate input directory if one is not supplied.
opts[:sites_yaml_folder] = "sites" unless opts[:sites_yaml_folder]
opts[:sites_alias_folder] = "sites" unless opts[:sites_alias_folder]

# Start a new sitelist and dbmapping with the first site
sitelist_file_mode = "w"
dbmapping_file_mode = "w"

cur_path = File.expand_path(".",Dir.pwd)
sites_yaml_path = cur_path + "/sites"
templates_path = cur_path + "/templates/features/auto_generate"
utils_path = File.expand_path("..",Dir.pwd) 
output_path = File.expand_path("../..",Dir.pwd)

# first argument needs to be site name or site alias listed in the site_map below to run qa_generate for a single site
site_name_param = ARGV[0] ? ARGV[0] : ""

site_alias_file = opts[:sites_alias_folder] + "/_sites_alias.txt" if File.directory?(opts[:sites_alias_folder])
site_alias_file = File.open(site_alias_file) or die "Unable to open site alias file..."
#FileUtils.cp(site_alias_file, output_path + "/features/support/") #file copy file not required for now

sites_alias_map = Hash.new
site_alias_file.each_line do |line| 
	vals = line.split("=")
	sites_alias_map[vals[0]] = vals[1].gsub(/\n/,"") 
end

#sites_alias_map = {"jmb" => "jojomamanbebe"}

site_name = site_name_param != "" ? (sites_alias_map[site_name_param] ? sites_alias_map[site_name_param] : site_name_param ) : "<site_name>"

num_sites = 0

# Generate sites list
autosites_filename = output_path + "/features/support/auto_sites.txt"
plog("Generating #{autosites_filename}...","grey") unless sitelist_file_mode == "a" if(site_name_param == "")
FileUtils.mkpath File.dirname(autosites_filename)

# Generate db mapping
dbmapping_filename = output_path + "/features/support/auto_dbmapping.yaml"
plog("Generating #{dbmapping_filename}...","grey") unless dbmapping_file_mode == "a" if(site_name_param == "")
FileUtils.mkpath File.dirname(dbmapping_filename)

plog("## Templates, Features, Scenarios, Step Definitions - Auto-generated by QA Generator v#{QA_GENERATE_VERSION} ##","grey")

if(site_name == "<site_name>" )
	plog("CONFIG =>","grey")
	plog("\tLocation of config files:","grey")
	plog("\tSite config YAML files \t\t=> #{sites_yaml_path}/","grey")
	plog("\tFeature templates \t\t=> #{templates_path}/","grey")
	plog("\tStep definition code \t\t=> #{output_path}/features/step_definitions","grey")
	plog("\tSupport modules per page type \t=> #{templates_path}/support/pages/","grey")
	plog("OUTPUT =>","grey")
	plog("\tLocation of generated files:","grey")
	plog("\tFeature files for each site \t=> #{output_path}/features/auto_generate/integration","grey")
	plog("\tSupport modules per page type \t=> #{output_path}/features/support/pages/","grey")
else
	begin
		site_check = Psych.load_file("sites/#{site_name}.yaml")
		rescue Exception => e  
		plog("QA Generate FAILED : Could not find an alias or site configuration file with name #{site_name}.yaml in your /utils/qa_generate/sites folder.","red")
		abort("")
	end
	plog("#{site_name.upcase} CONFIG LOCATION  => #{sites_yaml_path}/#{site_name}.yaml","grey")
	#plog("\tSite config file\t   : #{sites_yaml_path}/#{site_name}.yaml","grey")
	plog("#{site_name.upcase} OUTPUT LOCATIONS =>","grey")
	#plog("\tFeature file \t\t:: #{output_path}/features/auto_#{site_name}_integration.feature","grey")
	#plog("\tSupport modules \t:: #{output_path}/support/pages/site/","grey")
end

plog("GENERATE => ","grey")  if site_name == "<site_name>"

def generate_files(site, site_name, opts, output_path, do_for_all_sites)

	# Ensure there is a trailing slash
	template_directory = opts[:templates].dup
	template_directory << '/' if template_directory[-1].chr != '/'

	template_files = Dir[template_directory+"**/*"]

	# Generate output files from templates for site
	#plog("\t#{site_name.upcase} \t :: Generated feature files, scenarios and step definition code","grey") if do_for_all_sites
	files = Array.new
	template_files.each do |template_filename| 
	  #plog("template file is => #{template_filename} :: #{File.file?(template_filename)}", "grey")
		if File.file?(template_filename)
			template_file = File.open(template_filename, "r") { |f| f.read }
			generator = ERB.new(template_file, 0, "<>")
			generator.filename = template_filename
			output_content = generator.result(binding)
			output_filename = output_path + "/" + template_filename.gsub(/#{template_directory}/,'').gsub(/site/, site["site_name"])
			if (output_content =~ /\A#ignore/) then
				# puts "Skipping #{output_filename}. No tests to run." 
			else
				FileUtils.mkpath File.dirname(output_filename)
				output_file = File.open(output_filename, "w")
				output_file << output_content
				filename = template_filename.split("/")[-1].gsub(/site/, site["site_name"])
				if output_filename.include?(".feature")
					plog("\tFeature file \t=> #{output_filename}","grey") unless do_for_all_sites
				else
					files << filename
				end
				
			end
		end 
	end
	plog("\tSupport modules => #{output_path}/support/pages/","grey") unless do_for_all_sites
	if !do_for_all_sites && files.length > 4
		plog("\t\t\t   : #{files[0..3].join(", ")}","grey") 
	    plog("\t\t\t   : #{files[4..-1].join(", ")}","grey") 
	else
		plog("\t\t\t   : #{files.join(", ")}","grey") if !do_for_all_sites 
	end
	return true
end

def list_sites_generated(site_names)
	site_names_grouped = site_names.group_by{ |name| name[0] }
	site_names_grouped.each do |k, v|
		grouped_site_names = ""
		site_ctr = 0
		split_ctr =0
		v.each_with_index do |s_name, index|
			site_ctr = site_ctr + 1
			grouped_site_names = grouped_site_names == "" ? s_name : grouped_site_names + ", " + s_name 
			if site_ctr%10 == 0
				split_ctr = split_ctr + 10
				plog("\t#{grouped_site_names[0]} (10)\t=> #{grouped_site_names}","yellow")
				grouped_site_names = ""
			end
		end
		plog("\t#{grouped_site_names[0]} (#{split_ctr>0 ? site_ctr - split_ctr : site_ctr}) \t=> #{grouped_site_names}","yellow") if grouped_site_names != ""
	end
end

if(site_name!="<site_name>") 
	site_file = Psych.load_file("sites/#{site_name}.yaml")
	# Generate output files from templates for site
	generate_files(site_file,site_name,opts,output_path,do_for_all_sites=false)
	plog("## Auto-generation completed for #{site_name.upcase} ##","grey")
else
	# Ensure config and templates folders exist 
	Trollop::die :sites_yaml_folder, "File: '#{opts[:sites_yaml_folder]}' must exist" unless File.exist?(opts[:sites_yaml_folder])
	Trollop::die :templates, "File: '#{opts[:templates]}' must exist" unless File.exist?(opts[:templates])

	sites_file_path = opts[:sites_yaml_folder]
    sites_file_path += "/*.yaml" if File.directory?(sites_file_path)
	
	# output_path = opts[:outfile].dup
	# output_path = "../../" unless opts[:outfile]
	# output_path << '/' if output_path[-1].chr != '/'
	# output_path = File.dirname(__FILE__)

	site_files = Dir[sites_file_path]
	num_sites = site_files.length
	plog("\tGenerating feature files, scenarios and steps for #{num_sites} sites...","grey") #if do_for_all_sites
	site_names = Array.new
	site_files.each do |site_filename|
		# Load the site YAML file
		#site = YAML::load(File.open(site_filename, 'r:utf-8'))
		site_file = Psych.load_file(site_filename)

		# Generate output files from templates
		site_name = site_filename.partition('/').last.partition('.').first
		site_names << site_name.capitalize!
		generate_files(site_file,site_name,opts,output_path,do_for_all_sites=true)

		File.open(autosites_filename, sitelist_file_mode) do |asfile|
			site_name = site_file["home_page"]["URL"]
			site_name.gsub!(/https?:\/\//,'')
			site_name.gsub!(/www\./,'')
			site_name.gsub!(/\/.*$/, '')
			asfile.puts site_file["home_page"]["URL"] + "\n"
		end
		sitelist_file_mode = "a"
		File.open(dbmapping_filename, dbmapping_file_mode) do |dbmfile|
			dbmfile.puts "#{site_file["site_name"]}:\n"
			dbmfile.puts "  db: #{site_file["database_num"]}" unless site_file["database_num"].nil?
			dbmfile.puts "  site_id: #{site_file["site_id"]}" unless site_file["site_id"].nil?
		end
		dbmapping_file_mode = "a"
	
	end
	list_sites_generated(site_names)
	plog("<<<< QA_GENERATE DONE FOR #{num_sites} SITES >>>>","grey")
end
