#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Gant
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.gant.co.uk/mens-jeans/"
      direct_url URL      

    end  
end
