#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Gant
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.com/womens/t-shirts/details/40216/vintage-logo-t-shirt"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :value => "Add to bag")
      
    end  
end
