#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Dorothyperkinsmy
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://my.dorothyperkins.com/en/dpmy/product/clothing-1537608/dresses-1537829/green-34-midi-tube-dress-2137194?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
