#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Dorothyperkinsmy
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://my.dorothyperkins.com/en/dpmy/category/clothing-1537608/dresses-1537829"
      direct_url URL      

    end  
end
