#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Isabellaoliver
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.isabellaoliver.com/maternity-clothes/uk/100/maternity-tops.html?viewall=true"
      direct_url URL      

    end  
end
