#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Isabellaoliver
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.isabellaoliver.com/uk/shop/maternity-clothes/maternity-dresses/serafina-maternity-dress-dark-grey-melange.htm"
      direct_url URL
	  # site elements
      
      span(:add_to_basket, :id=> "cartButtonSubmit")
       
      # page elements
      
      button(:add_to_basket, :class=> "btn-lg btn-major fr no-margin")
      
    end  
end
