#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Superdryit
	class ProductPage
		include PageObject
		include PeeriusHelper
		# site elements
		 
		
		# page elements
		
		button(:add_to_basket, :src=> "http://www.superdry.it/public/images/languages/it-IT/product/add-to-bag.png")
		



	end  
end
