#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Jojomamanbebe
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.jojomamanbebe.co.uk/sp+mini-bath-tub-in-bathtime-and-healthcare+b9169"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :id=> "iB1")
       
      # page elements
      
      button(:add_to_basket, :id=> "iB1")
      
    end  
end
