#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Jojomamanbebe
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.jojomamanbebe.co.uk/pp+maternity-tunics-and+shirts"
      direct_url URL      

    end  
end
