#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Dawsons
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.dawsons.co.uk/checkout/onepage/"
		direct_url URL    
    end  
end
