#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Evanseu
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://euro.evansfashion.com/en/eveu/product/accessories-927599/belts-927618/evans-black-keeper-waist-belt-2067532?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
