<% if site["ignore"] or site["ignore_web"]%>
#ignore
<% end %>
#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %>
#

<% if site["product_page"] %>
<% page = site["product_page"] %>
module <%= site["site_name"].capitalize %>
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "<%= debug_url(page["URL"]) %>"
      direct_url URL
	  # site elements
      <% if site["add_to_basket_button"] %>
      <%= site["add_to_basket_button"][0] %>(:add_to_basket, <%= site["add_to_basket_button"][1] %>)
      <% end %> 
      # page elements
      <% if page["add_to_basket_button"] %>
      <%= page["add_to_basket_button"][0] %>(:add_to_basket, <%= page["add_to_basket_button"][1] %>)
      <% end %>
      
      def get_site_custom_js
        <% if site["site_custom_js"] != nil %>
          return "<%= site["site_custom_js"] %>"
        <% else %>
          return nil
        <% end %>
      end 
    end  
end
<% end %>