#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Superdrychchde
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.superdrystore.ch/ch-de/checkout"
		direct_url URL    
    end  
end
