#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Superdrychchde
	class ProductPage
		include PageObject
		include PeeriusHelper
		# site elements
		 
		
		# page elements
		
		button(:add_to_basket, :src=> "http://www.superdrystore.ch/ch-de/public/images/languages/de-DE/product/add-to-bag.png")
		



	end  
end
