#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Superdrychchde
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdrystore.ch/ch-de/damen/chinos"
      direct_url URL      

    end  
end
