#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Frenchconnection
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.frenchconnection.com/category/Woman+Collections+Dresses/Dresses.htm"
      direct_url URL            
    end  
end