#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Frenchconnection
  
    class CheckoutPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.frenchconnection.com/checkout.htm#"
      direct_url URL            
    end  
end