#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Frenchconnection
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.frenchconnection.com/search/keywords+are+abcd/abcd.htm"
      direct_url URL            
    end  
end