#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Frenchconnection
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.frenchconnection.com/search/keywords+are+dvd/dvd.htm"
      direct_url URL            
    end  
end
