#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
module Frenchconnection
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.frenchconnection.com/"
      direct_url URL
      
      link(:login_link, :title => "Sign In")
	    text_field(:search, :id => "ctl00_ctl00_txtKeywordSearch")
    end  
end