#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Neweracap
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.neweracap.co.uk/59fifty-fitted-dept021_pg1/"
      direct_url URL            
    end  
end