#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
module Neweracap
  
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "www.neweracap.co.uk/"
      direct_url URL
      
      link(:login_link, :title => "MY ACCOUNT")
	    text_field(:search, :id => "searchINPUT")
    end  
end