#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Neweracap
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.neweracap.co.uk/my-first-atlanta-braves-infants-59fifty-prod10706312/"
      direct_url URL
      
      button(:add_to_basket, :name=> "img_add_to_basket1")          
    end  
end