#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topshop
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.topshop.com/webapp/wcs/stores/servlet/OrderItemDisplay?catalogId=33057&langId=-1&storeId=12556"
      direct_url URL
      
      link(:basket_checkout, :class => "btn_checkout")
      
       
      
      def remove_product_links
        link_elements(:class => "remove_bag_item")
      end 
      
    end  
end
