#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4 on 2013-02-03 16:02:18 +0000
#

module Topshop
    class CheckoutPage
      include PageObject
      include PeeriusHelper
      
      URL = ""
      direct_url URL            
    end  
end