#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4
#

module Topshop
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.topshop.com/webapp/wcs/stores/servlet/ProductDisplay?beginIndex=1&viewAllFlag=&catalogId=33057&storeId=12556&productId=8775006&langId=-1&sort_field=Relevance&categoryId=208568&parent_categoryId=208495&pageSize=20"
      direct_url URL
      
      button(:add_to_basket, :class=> "btn_add_2_shop_cart")          
    end  
end