#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4 on 2013-02-02 21:24:37 +0000
#

module Topshop
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.topshop.com/webapp/wcs/stores/servlet/ProductDisplay?beginIndex=1&viewAllFlag=&catalogId=33057&storeId=12556&productId=9134142&langId=-1&sort_field=Relevance&categoryId=208523&parent_categoryId=203984&pageSize=20"
      direct_url URL
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      select_list(:size_select, :id => "product_size_full")            
    end  
end