#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Tommyhilfigeres
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://es.tommy.com/Caswell-Camisa-Denim/0887838173,es_ES,pd.html?cgid=203000#!color%3D984%26i%3D7"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :class=> "button active addtocartbutton a")
      
    end  
end
