#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Tommyhilfigeres
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://es.tommy.com/on/demandware.store/Sites-ES-Site/es_ES/Search-Show?q=shirt"
      direct_url URL            
    end  
end
