#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Zavvi
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.zavvi.com/SearchNoResults.aspx?term=abc"
      direct_url URL            
    end  
end