#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Zavvi
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.zavvi.com/blu-ray.dept"
      direct_url URL            
    end  
end