#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Tommyhilfigerchfr
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://ch.tommy.com/on/demandware.store/Sites-CH-Site/fr_CH/Cart-Show"
      direct_url URL
      
      button(:basket_checkout, :name => "dwfrm_cart_checkoutCart")
      
       
      
      def remove_product_links
        button_elements(:class => "remove no_print")
      end 
      
    end  
end
