#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140623
#

module Zoogigant
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.zoogigant.de/findologic.php"
      direct_url URL            
    end  
end
