#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Cathkidston
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.cathkidston.co.uk/searchadv.aspx?SearchTerm=bag"
      direct_url URL            
    end  
end
