#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Cathkidston
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.cathkidston.co.uk/checkoutreview.aspx?paymentmethod=CREDIT+CARD"
		direct_url URL    
    end  
end
