#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Cathkidston
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.cathkidston.co.uk/c-486-cath-kidston-messenger-bags.aspx"
      direct_url URL      

    end  
end
