#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Cathkidston
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.cathkidston.co.uk/p-19941-cath-kidston-kentish-rose-weekend-bag.aspx?referrer=category"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :class=> "AddToCartButton")
      
    end  
end
