#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Microscootersuk
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.micro-scooters.co.uk/basket"
      direct_url URL
      
      image(:basket_checkout, :id => "checkoutbtn2")
      
       
      
      def remove_product_links
        image_elements(:src => "images/remove.png")
      end 
      
    end  
end
