#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Microscootersuk
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.micro-scooters.co.uk/product/mx-trixx-scooter/"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "input-add")
      
    end  
end
