#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Jakoo
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.jako-o.com/products-kids-fashion-girls-fashion-size-92-158-long-sleeves-and-sweatshirts--00004045/"
      direct_url URL      

    end  
end
