#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Frenchconnectionus
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://usa.frenchconnection.com/category/man+Collections+jeans/Mens+Jeans.htm"
      direct_url URL      

    end  
end
