#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Alexandalexa
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.alexandalexa.com/il-gufo-and-white-cotton-dress-navy"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :xpath=> "//form[@id=\"product_addtocart_form\"]/div/div/div/div/button")
       
      # page elements
      
    end  
end
