#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Alexandalexa
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.alexandalexa.com/checkout/onepage/"
		direct_url URL    
    end  
end
