#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Alexandalexa
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.alexandalexa.com/customer/account/login/"
      direct_url URL
      
  	  text_field(:username, :id=>"email")
      text_field(:password, :id=>"pass")  
  	  button(:login_submit, :id=>"send2")           
    end  
end
