#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Topmanfr
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://fr.topman.com/fr/tmfr/cat%C3%A9gorie/v%C3%AAtements-homme-586411/jeans-hommes-586417"
      direct_url URL      

    end  
end
