#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Cottontraders
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.cottontraders.co.uk/bin/venda?ex=co_wizr-register&bsref=cottontraders"
      direct_url URL
      
  	  text_field(:username, {:id=>"email", :index => 1})
      text_field(:password, :id=>"password")  
  	  button(:login_submit, :class =>"right")           
    end  
end

