#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Cottontraders
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.cottontraders.co.uk/accessories/performance-cap/invt/ah10496/"
      direct_url URL
      
      link(:add_to_basket, :href=> "http://www.cottontraders.co.uk/bin/venda?bsref=cottontraders&log=22&mode=add&ex=co_disp-shopc&buy=ah10496&invt=ah10496&ivref=ah10496&qty=1&att1=One size&att2=Black&att3=&att4=&qty=1")          
    end  
end