#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Cottontraders
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.cottontraders.co.uk/bin/venda?ex=co_wizr-register&bsref=cottontraders"
      direct_url URL
      
  	  text_field(:username, :id => "email")
      text_field(:password, :id=>"password")  
  	  button(:login_submit, :class =>"button buttonAlt submit")           
    end  
end
