#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Cottontraders
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.cottontraders.com/stretch-turtle-neck-top/invt/aa12620"
      direct_url URL
	  # site elements
      
      link(:add_to_basket, :xpath=> "//div[@id=\"prodpageBasketButton\"]/a")
       
      # page elements
      
      link(:add_to_basket, :title=> "Click to proceed")
      
    end  
end
