#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Cottontraders
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.cottontraders.com/mens-shirts/all-mens-shirts-/icat/mens-shirts-all&bklist=icat,5,shop,mens,mensshirts,mens-shirts-all"
      direct_url URL      

    end  
end
