#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Cottontraders
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.cottontraders.co.uk/search?q=aaa&searchsubmit=Search&categories=shop"
      direct_url URL            
    end  
end