#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Wallis
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wallis.co.uk/webapp/wcs/stores/servlet/ProductDisplay?catalogId=33058&storeId=12557&productId=13258165&langId=-1"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
