#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Wallis
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.wallis.co.uk/webapp/wcs/stores/servlet/OrderItemDisplay?catalogId=33058&langId=-1&storeId=12557&ddkey=http:OrderCalculate"
      direct_url URL
      
      link(:basket_checkout, :class => "btn_checkout")            
    end  
end