#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Wallis
  
    class CheckoutPage
      include PageObject
      include PeeriusHelper
      
      URL = ""
      direct_url URL            
    end  
end