#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Wallis
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wallis.co.uk/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?catalogId=33058&storeId=12557&langId=-1&viewAllFlag=false&sort_field=Relevance&categoryId=209327&beginIndex=1&pageSize=20"
      direct_url URL            
    end  
end