#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4
#
Feature: Wickes Integration
                                                                                                
@wickes
Scenario: Wickes home page is tracked correctly
	Given I am on the wickes home page
	Then it should be tracked as a home page
	And the debug info should show no SMART-recs

@wickes
Scenario: Wickes category page is tracked correctly
    Given I am on the wickes category page
    Then it should be tracked as a Category page

@wickes
Scenario: Wickes product page is tracked correctly
    Given I am on the wickes product page
    Then it should be tracked as a product page
    
@wickes
Scenario: Wickes basket page is tracked correctly
    Given I am on the wickes basket page
    Then it should be tracked as a basket page    
        
@wickes
Scenario: Wickes checkout page is tracked correctly
	Given I am on the wickes home page
	When I click login
	And I login as "webtest@mailinator.com" using password "webtest"
	And I go to the product page
	And I add the current product to the basket
	And I go to the basket page
	And I click checkout
	Then it should be tracked as a Checkout page
  
@wickes 
Scenario: Wickes search results page is tracked correctly
    Given I am on the wickes homepage
    When I search for "ladder"
    Then it should be tracked as a search results page

#
# SMART-recs
# 		
@wickes 
Scenario: Wickes zero search recommendations are shown
    Given I am on the wickes homepage
    When I search for "nappies"
    Then it should be tracked as a search results page
    And the debug info should show at least 1 SMART-recs
				

@wickes
Scenario: SMART-recs appear on Wickes product page
    Given I am on the wickes product page
    Then the debug info should show at least 1 SMART-recs

