#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#
@neweracap
Feature: NewEraCap Integration

#
# Tracking tests
#


Scenario: NewEraCap home page is tracked correctly
  Given I am on the neweracap home page
#  And I clear my browser cookies
  
  Then it should be tracked as a home page
  And the debug info should show no SMART-recs

Scenario: NewEraCap category page is tracked correctly
  Given I am on the neweracap category page
#  And I clear my browser cookies
  
  Then it should be tracked as a category page
  And the debug info should show no SMART-recs

Scenario: NewEraCap product page is tracked correctly
  Given I am on the neweracap product page
#  And I clear my browser cookies
  
  Then it should be tracked as a product page
  And the debug info should show at least 11 SMART-recs

Scenario: NewEraCap basket page is tracked correctly
  Given I am on the neweracap basket page
#  And I clear my browser cookies
  
  Then it should be tracked as a basket page
  And the debug info should show at least 5 SMART-recs


Scenario: NewEraCap checkout page is tracked correctly
  Given I am on the neweracap home page
#  And I clear my browser cookies
  
  When I click login
  And I login as "anagha.joshi@peerius.com" using password "Pa55word"
  And I go to the product page
  
  And I add the current product to the basket
  And I pause for 2 seconds
  And I go to the basket page
  And I click checkout
  And I click on the link with class "btn_proceed_to_payment submit_button chk_button_primary"
  
  Then it should be tracked as a Checkout page
  And the debug info should show no SMART-recs

Scenario: NewEraCap search results page is tracked correctly
    Given I am on the neweracap homepage
#    And I clear my browser cookies
    
    When I search for "shirts"
    Then it should be tracked as a search results page
    And the debug info should show no SMART-recs

#
# Zero search tests
#
@zerosearch
Scenario: NewEraCap zero search recommendations are shown
    Given I am on the neweracap homepage
#    And I clear my browser cookies
    
    When I search for "dvd"
    Then it should be tracked as a search results page
    And the debug info should show at least 1 SMART-recs

