#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#
@thewhitecompany

Feature: thewhitecompany Integration

#
# Tracking tests
#


Scenario: thewhitecompany home page is tracked correctly
  Given I am on the thewhitecompany home page
  And I clear my browser cookies
  
  Then it should be tracked as a home page
  And the debug info should show no SMART-recs

Scenario: thewhitecompany category page is tracked correctly
  Given I am on the thewhitecompany category page
  And I clear my browser cookies
  
  Then it should be tracked as a category page
  And the debug info should show no SMART-recs

Scenario: thewhitecompany product page is tracked correctly
  Given I am on the thewhitecompany product page
  And I clear my browser cookies
  
  Then it should be tracked as a product page
  And the debug info should show at least 3 SMART-recs

Scenario: thewhitecompany basket page is tracked correctly
  Given I am on the thewhitecompany basket page
  And I clear my browser cookies
  
  Then it should be tracked as a basket page
  And the debug info should show at least 3 SMART-recs


Scenario: thewhitecompany checkout page is tracked correctly
  Given I am on the thewhitecompany home page
When I click login
And I login as "faiyyaz.sultana@peerius.com" using password "Pa55word"
And I go to the product page
And I click on the img with alt "More"
And I add the current product to the basket
And I go to the basket page
And I click checkout
And I click on the button with id "in_btnProceed"
And I enter the payment details
Then it should be tracked as a Checkout page
And the debug info should show no SMART-recs
Scenario: thewhitecompany search results page is tracked correctly
    Given I am on the thewhitecompany homepage
    And I clear my browser cookies
    
    When I search for "towel"
    Then it should be tracked as a search results page
    And the debug info should show no SMART-recs


