#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#
@wickes
Feature: Wickes Integration

#
# Tracking tests
#


Scenario: Wickes home page is tracked correctly
  Given I am on the wickes home page
#  And I clear my browser cookies
  
  
  Then it should be tracked as a home page
  And the debug info should show no SMART-recs

Scenario: Wickes category page is tracked correctly
  Given I am on the wickes category page
#  And I clear my browser cookies
  
  
  Then it should be tracked as a category page
  And the debug info should show no SMART-recs

Scenario: Wickes product page is tracked correctly
  Given I am on the wickes product page
#  And I clear my browser cookies
  
  
  Then it should be tracked as a product page
  And the debug info should show at least 6 SMART-recs

Scenario: Wickes basket page is tracked correctly
  Given I am on the wickes basket page
#  And I clear my browser cookies
  
  
  Then it should be tracked as a basket page
  And the debug info should show at least 6 SMART-recs


Scenario: Wickes checkout page is tracked correctly
  Given I am on the wickes home page
#  And I clear my browser cookies
  
  When I click login
  And I login as "webtest@mailinator.com" using password "webtest"
  And I go to the product page
  
  And I add the current product to the basket
  And I pause for 2 seconds
  And I go to the basket page
  And I click checkout
  
  Then it should be tracked as a Checkout page
  And the debug info should show no SMART-recs

Scenario: Wickes search results page is tracked correctly
    Given I am on the wickes homepage
#    And I clear my browser cookies
    
    When I search for "ladder"
    Then it should be tracked as a search results page
    And the debug info should show no SMART-recs


