#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#
@redletterdays
Feature: Red Letter Days Integration

#
# Tracking tests
#


Scenario: Red Letter Days home page is tracked correctly
  Given I am on the redletterdays home page
#  And I clear my browser cookies
  
  And I use the SPR key
  
  
  Then it should be tracked as a home page
  And the debug info should show no SMART-recs

Scenario: Red Letter Days category page is tracked correctly
  Given I am on the redletterdays category page
#  And I clear my browser cookies
  
  
  Then it should be tracked as a category page
  And the debug info should show no SMART-recs

Scenario: Red Letter Days product page is tracked correctly
  Given I am on the redletterdays product page
#  And I clear my browser cookies
  
  
  Then it should be tracked as a product page
  And the debug info should show at least 7 SMART-recs

Scenario: Red Letter Days basket page is tracked correctly
  Given I am on the redletterdays basket page
#  And I clear my browser cookies
  
  
  Then it should be tracked as a basket page
  And the debug info should show at least 1 SMART-recs


Scenario: Red Letter Days checkout page is tracked correctly
  Given I am on the redletterdays home page
#  And I clear my browser cookies
  
  When I click login
  And I login as "webtest@mailinator.com" using password "webtest"
  
  And I go to the product page
  
  And I add the current product to the basket
  And I pause for 2 seconds
  And I go to the basket page
  And I click checkout
  And I click on the button with id "ctl00_contentBody_submit"
  
  Then it should be tracked as a Checkout page
  And the debug info should show no SMART-recs

Scenario: Red Letter Days search results page is tracked correctly
    Given I am on the redletterdays homepage
#    And I clear my browser cookies
    
    When I search for "shirts"
    Then it should be tracked as a search results page
    And the debug info should show no SMART-recs

#
# Zero search tests
#
@zerosearch
Scenario: Red Letter Days zero search recommendations are shown
    Given I am on the redletterdays homepage
#    And I clear my browser cookies
    
    When I search for "dvd"
    Then it should be tracked as a search results page
    And the debug info should show at least 1 SMART-recs

