#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
@notonthehighstreet
Feature: Not on the High Street Integration

#
# Tracking tests
#
                                                                                                
Scenario: Not on the High Street home page is tracked correctly
  Given I am on the notonthehighstreet home page
  Then it should be tracked as a home page
  And the debug info should show no SMART-recs

Scenario: Not on the High Street category page is tracked correctly
    Given I am on the notonthehighstreet category page
    Then it should be tracked as a Category page
    And the debug info should show at least 1 SMART-recs

Scenario: Not on the High Street product page is tracked correctly
    Given I am on the notonthehighstreet product page
    Then it should be tracked as a product page
    And the debug info should show at least 3 SMART-recs
    
Scenario: Not on the High Street basket page is tracked correctly
    Given I am on the notonthehighstreet basket page
    Then it should be tracked as a basket page
    And the debug info should show at least 1 SMART-recs    
       
Scenario: Not on the High Street checkout page is tracked correctly
  Given I am on the notonthehighstreet home page
  When I click login
  And I login as "webtest@mailinator.com" using password "webtest"
  And I go to the product page
  And I add the current product to the basket
  And I go to the basket page
  And I click checkout
  Then it should be tracked as a Checkout page
  And the debug info should show no SMART-recs
  
Scenario: Not on the High Street search results page is tracked correctly
    Given I am on the notonthehighstreet homepage
    When I search for "map"
    Then it should be tracked as a search results page
    And the debug info should show no SMART-recs


