#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#
@bakerross

Feature: Baker Ross Integration

#
# Tracking tests
#


Scenario: Baker Ross home page is tracked correctly
  Given I am on the bakerross home page
  And I clear my browser cookies
  
  Then it should be tracked as a home page
  And the debug info should show at least 1 SMART-recs

Scenario: Baker Ross category page is tracked correctly
  Given I am on the bakerross category page
  And I clear my browser cookies
  
  Then it should be tracked as a category page
  And the debug info should show no SMART-recs

Scenario: Baker Ross product page is tracked correctly
  Given I am on the bakerross product page
  And I clear my browser cookies
  
  Then it should be tracked as a product page
  And the debug info should show at least 1 SMART-recs

Scenario: Baker Ross basket page is tracked correctly
  Given I am on the bakerross basket page
  And I clear my browser cookies
  
  Then it should be tracked as a basket page
  And the debug info should show at least 1 SMART-recs


Scenario: Baker Ross checkout page is tracked correctly
  Given I am on the bakerross home page
When I go to the product page
And I add the current product to the basket
And I go to the basket page
And I click checkout
And I click on the element with id "rdPassword2"
And I login as "webtest@mailinator.com" using password "webtest"
And I click on the link with href "javascript:termsAndConditions()"
Then it should be tracked as a Checkout page
And the debug info should show no SMART-recs

Scenario: Baker Ross search results page is tracked correctly
    Given I am on the bakerross homepage
    And I clear my browser cookies
    
    When I search for "blue"
    Then it should be tracked as a search results page
    And the debug info should show no SMART-recs

#
# Zero search tests
#
@zerosearch
Scenario: Baker Ross zero search recommendations are shown
    Given I am on the bakerross homepage
    And I clear my browser cookies
    
    When I search for "nappies"
    Then it should be tracked as a search results page
    And the debug info should show at least 1 SMART-recs

