#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
Feature: Cotton Traders Integration
                                                                                                
@cottontraders
Scenario: Cotton Traders home page is tracked correctly
	Given I am on the cottontraders home page
	Then it should be tracked as a home page
	And the debug info should show at least 1 SMART-recs

@cottontraders
Scenario: Cotton Traders category page is tracked correctly
    Given I am on the cottontraders category page
    Then it should be tracked as a Category page
    And the debug info should show at least 1 SMART-recs

@cottontraders
Scenario: Cotton Traders product page is tracked correctly
    Given I am on the cottontraders product page
    Then it should be tracked as a product page
    And the debug info should show at least 1 SMART-recs
    
@cottontraders
Scenario: Cotton Traders basket page is tracked correctly
    Given I am on the cottontraders basket page
    Then it should be tracked as a basket page
    And the debug info should show at least 1 SMART-recs    
       
@cottontraders
Scenario: Cotton Traders checkout page is tracked correctly
	Given I am on the cottontraders home page
	When I click login
	And I login as "webtest@mailinator.com" using password "webtest"
	And I go to the product page
	And I add the current product to the basket
	And I go to the basket page
	And I click checkout
	Then it should be tracked as a Checkout page
	And the debug info should show no SMART-recs
  
@cottontraders 
Scenario: Cotton Traders search results page is tracked correctly
    Given I am on the cottontraders homepage
    When I search for "shirt"
    Then it should be tracked as a search results page
    And the debug info should show no SMART-recs

#
# SMART-recs
# 		
@cottontraders @zerosearch
Scenario: Cotton Traders zero search recommendations are shown
    Given I am on the cottontraders homepage
    When I search for "asdf"
    Then it should be tracked as a search results page
    And the debug info should show at least 1 SMART-recs

