#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
@mandco
Feature: Mandco Integration

#
# Tracking tests
#
                                                                                                
Scenario: Mandco home page is tracked correctly
  Given I am on the mandco home page
  Then it should be tracked as a home page
  And the debug info should show no SMART-recs

Scenario: Mandco category page is tracked correctly
    Given I am on the mandco category page
    Then it should be tracked as a Category page
    And the debug info should show no SMART-recs

Scenario: Mandco product page is tracked correctly
    Given I am on the mandco product page
    Then it should be tracked as a product page
    And the debug info should show at least 3 SMART-recs
    
Scenario: Mandco basket page is tracked correctly
    Given I am on the mandco basket page
    Then it should be tracked as a basket page
    And the debug info should show no SMART-recs    
       
Scenario: Mandco checkout page is tracked correctly
  Given I am on the mandco home page
  When I click login
  And I login as "anagha.joshi@peerius.com" using password "123123"
  And I go to the product page
  And I add the current product to the basket
  And I go to the basket page
  And I click checkout
  Then it should be tracked as a Checkout page
  And the debug info should show no SMART-recs
  
Scenario: Mandco search results page is tracked correctly
    Given I am on the mandco homepage
    When I search for "dress"
    Then it should be tracked as a search results page
    And the debug info should show no SMART-recs


