#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
Feature: Zavvi Integration
                                                                                                
@zavvi
Scenario: Zavvi home page is tracked correctly
	Given I am on the zavvi home page
	Then it should be tracked as a home page
	And the debug info should show at least 3 SMART-recs

@zavvi
Scenario: Zavvi category page is tracked correctly
    Given I am on the zavvi category page
    Then it should be tracked as a Category page
    And the debug info should show no SMART-recs

@zavvi
Scenario: Zavvi product page is tracked correctly
    Given I am on the zavvi product page
    Then it should be tracked as a product page
    And the debug info should show no SMART-recs
    
@zavvi
Scenario: Zavvi basket page is tracked correctly
    Given I am on the zavvi basket page
    Then it should be tracked as a basket page
    And the debug info should show at least 2 SMART-recs    
       
@zavvi
Scenario: Zavvi checkout page is tracked correctly
	Given I am on the zavvi home page
	When I click login
	And I login as "testmail@123.com" using password "pass1234"
	And I go to the product page
	And I add the current product to the basket
	And I go to the basket page
	And I click checkout
	Then it should be tracked as a Checkout page
	And the debug info should show no SMART-recs
  
@zavvi 
Scenario: Zavvi search results page is tracked correctly
    Given I am on the zavvi homepage
    When I search for "dvd"
    Then it should be tracked as a search results page
    And the debug info should show no SMART-recs


