#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4 on 2013-02-02 21:24:37 +0000
#
Feature: Topshop Integration

@topshop
Scenario: Topshop home page is tracked correctly
	Given I am on the topshop home page
	Then it should be tracked as a home page

@topshop
Scenario: Topshop category page is tracked correctly
    Given I am on the topshop category page
    Then it should be tracked as a Category page

@topshop
Scenario: Topshop product page is tracked correctly
    Given I am on the topshop product page
    Then it should be tracked as a product page
    
@topshop
Scenario: Topshop basket page is tracked correctly
    Given I am on the topshop basket page
    Then it should be tracked as a basket page    
        
@topshop
Scenario: Topshop checkout page is tracked correctly
	Given I am on the topshop home page
	When I click login
	And I fill in my login details
	And I go to the product page
	And I add the current product to the basket
	And I go to the basket page
	And I click checkout
	Then it should be tracked as a Checkout page
		
@topshop 
Scenario: Topshop zero search recommendations are shown
    Given I am on the topshop homepage
    When I search for "dvd"
    Then I should end up on the search results page
    And I should see at least 1 SMART-recs
	
@topshop 
Scenario: Topshop search results page is tracked correctly
    Given I am on the topshop homepage
    When I search for "shirt"
    Then I should end up on the search results page
			
@topshop
Scenario: SMART-recs appear on Topshop product page
    Given I am on the topshop product page
    Then I should see SMART-recs
    And the debug info should show at least 1 SMART-recs

@topshop
Scenario: SMART-rec links work on Topshop product pages
    Given I am on the topshop product page
    And I click the first SMART-rec image link 
    Then I should end up on a product page
    And it should be tracked as a product page          
