#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#
@boohoo

Feature: boohoo Integration

#
# Tracking tests
#


Scenario: boohoo home page is tracked correctly
  Given I am on the boohoo home page
  
  Then it should be tracked as a home page
  And the debug info should show no SMART-recs

Scenario: boohoo category page is tracked correctly
  Given I am on the boohoo category page
  
  Then it should be tracked as a category page
  And the debug info should show no SMART-recs

Scenario: boohoo product page is tracked correctly
  Given I am on the boohoo product page
  
  Then it should be tracked as a product page
  And the debug info should show at least 7 SMART-recs

Scenario: boohoo basket page is tracked correctly
  Given I am on the boohoo basket page
  
  Then it should be tracked as a basket page
  And the debug info should show at least 1 SMART-recs


Scenario: boohoo checkout page is tracked correctly
  Given I am on the boohoo home page
  
  When I click login
  And I login as "webtest@mailinator.com" using password "webtest"
  And I go to the product page
  And I add the current product to the basket
  And I go to the basket page
  And I click checkout
  
  Then it should be tracked as a Checkout page
  And the debug info should show no SMART-recs

Scenario: boohoo search results page is tracked correctly
    Given I am on the boohoo homepage
    
    When I search for "shirts"
    Then it should be tracked as a search results page
    And the debug info should show no SMART-recs

#
# Zero search tests
#
@zerosearch
Scenario: boohoo zero search recommendations are shown
    Given I am on the boohoo homepage
    
    When I search for "dvd"
    Then it should be tracked as a search results page
    And the debug info should show at least 1 SMART-recs

