#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4 on 2013-02-05 15:01:50 +0000
#
Feature: Wickes Integration

@wickes
Scenario: Wickes home page is tracked correctly using SPR
	Given I am on the wickes home page
	And I use the SPR key
	Then it should be tracked as a home page

Scenario: Wickes home page is tracked correctly without SPR
	Given I am on the wickes home page
	Then it should be tracked as an other page

@wickes
Scenario: Wickes category page is tracked correctly
    Given I am on the wickes category page
    Then it should be tracked as a Category page

@wickes
Scenario: Wickes product page is tracked correctly
    Given I am on the wickes product page
    Then it should be tracked as a product page
    
@wickes
Scenario: Wickes basket page is tracked correctly
    Given I am on the wickes basket page
    Then it should be tracked as a basket page    
        
@wickes
Scenario: Wickes checkout page is tracked correctly
	Given I am on the wickes home page
	When I click login
	And I fill in my login details
	And I go to the product page
	And I add the current product to the basket
	And I go to the basket page
	And I click checkout
	Then it should be tracked as a Checkout page
		
@wickes 
Scenario: Wickes zero search recommendations are shown
    Given I am on the wickes homepage
    When I search for "dvd"
    Then I should end up on the search results page
    And I should see at least 1 SMART-recs
	
@wickes 
Scenario: Wickes search results page is tracked correctly
    Given I am on the wickes homepage
    When I search for "shirt"
    Then I should end up on the search results page
			
@wickes
Scenario: SMART-recs appear on Wickes product page
    Given I am on the wickes product page
    Then I should see SMART-recs
    And the debug info should show at least 1 SMART-recs

@wickes
Scenario: SMART-rec links work on Wickes product pages
    Given I am on the wickes product page
    And I click the first SMART-rec image link 
    Then I should end up on a product page
    And it should be tracked as a product page          
