#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#
@lookfantastic
Feature: Look Fantastic Integration

#
# Tracking tests
#
                                                                                                
Scenario: Look Fantastic home page is tracked correctly using SPR
  Given I am on the lookfantastic home page
  And I use the SPR key
  Then it should be tracked as a home page                                                               
  And the debug info should show no SMART-recs
  
Scenario: Look Fantastic home page is tracked correctly without SPR
  Given I clear my browser cookies
  And I am on the lookfantastic home page
  Then it should be tracked as an other page

Scenario: Look Fantastic category page is tracked correctly
    Given I am on the lookfantastic category page
    Then it should be tracked as a Category page
    And the debug info should show no SMART-recs

Scenario: Look Fantastic product page is tracked correctly
    Given I am on the lookfantastic product page
    Then it should be tracked as a product page
    And the debug info should show at least 7 SMART-recs
    
Scenario: Look Fantastic basket page is tracked correctly
    Given I am on the lookfantastic basket page
    Then it should be tracked as a basket page
    And the debug info should show at least 1 SMART-recs    
       
Scenario: Look Fantastic checkout page is tracked correctly
  Given I am on the lookfantastic home page
  When I click login
  And I login as "webtest@mailinator.com" using password "webtest"
  And I go to the product page
  And I add the current product to the basket
  And I go to the basket page
  And I click checkout
  Then it should be tracked as a Checkout page
  And the debug info should show no SMART-recs
  
Scenario: Look Fantastic search results page is tracked correctly
    Given I am on the lookfantastic homepage
    When I search for "shirts"
    Then it should be tracked as a search results page
    And the debug info should show no SMART-recs

#
# Zero search tests
#     
@zerosearch
Scenario: Look Fantastic zero search recommendations are shown
    Given I am on the lookfantastic homepage
    When I search for "dvd"
    Then it should be tracked as a search results page
    And the debug info should show at least 1 SMART-recs

