#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4
#
Feature: wallis Integration

@wallis
Scenario: wallis home page is tracked correctly
	Given I am on the wallis home page
	Then it should be tracked as a home page

@wallis
Scenario: wallis category page is tracked correctly
    Given I am on the wallis category page
    Then it should be tracked as a Category page

@wallis
Scenario: wallis product page is tracked correctly
    Given I am on the wallis product page
    Then it should be tracked as a product page
    
@wallis
Scenario: wallis basket page is tracked correctly
    Given I am on the wallis basket page
    Then it should be tracked as a basket page    
        
@wallis
Scenario: wallis checkout page is tracked correctly
	Given I am on the wallis home page
	When I click login
	And I fill in my login details
	And I go to the product page
	And I add the current product to the basket
	And I go to the basket page
	And I click checkout
	Then it should be tracked as a Checkout page
  
@wallis 
Scenario: wallis search results page is tracked correctly
    Given I am on the wallis homepage
    When I search for "shirt"
    Then it should be tracked as a search results page

#
# SMART-recs
# 		
@wallis 
Scenario: wallis zero search recommendations are shown
    Given I am on the wallis homepage
    When I search for "dvd"
    Then it should be tracked as a search results page
    Then the debug info should show at least 1 SMART-recs
				

@wallis
Scenario: SMART-recs appear on wallis product page
    Given I am on the wallis product page
    Then the debug info should show at least 1 SMART-recs

