#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Evans
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.evans.co.uk/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-1&storeId=12553&catalogId=33054&beginIndex=1&viewAllFlag=false&pageSize=24&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dvd&x=25&y=13"
      direct_url URL            
    end  
end
