#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Alexandalexa
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.alexandalexa.com/catalogsearch/result/?q=dvd"
      direct_url URL            
    end  
end
