#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Alexandalexa
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.alexandalexa.com/shoes/baby-toddler-shoes"
      direct_url URL      

    end  
end
