#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Alexandalexa
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.alexandalexa.com/checkout/cart/"
      direct_url URL
      
      button(:basket_checkout, :class => "button btn-proceed-checkout btn-checkout")
      
       
      
      def remove_product_links
        link_elements(:class => "remove-item")
      end 
      
    end  
end
