#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Bhssandpit
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.bhs.co.uk/webapp/wcs/stores/servlet/PaymentDetailsView?catalogId=34096&storeId=13077&langId=-1&krypto=rxXAlZb0YaVE9rEw5lOVD9M%2FOSLM2EBYuzlJq%2FiI3Xm%2BBDJ3yTf0dHtkBjeLdBbiXfViveSbdUkb%0Aaf1WIyVrpJ6kgCfhFgrkSZByT2TOcYiskl15KfDGI62%2FEnF3k1q6ugLsbmICsoj%2FWwBNU1m%2Fn9K4%0ADkatfdbcgyc5bVFQPuvT2arrZcdH6gcQU6nMYjv05ugwjqPtLts5ichHR6MW%2FLcS%2BL8h4C2rTat3%0AKZInCwPnHz6O2ykDUasvsk8UxZ6TUOmTeq74u%2B5Q%2Bk3hslgZb95ANgWU75nYxAmhr%2FiC%2FaeXolfs%0A1z8dAufyH21SSU0EBqXdwvQbE3xtypfWIWu2QiQGKGbDZuOz%2F90psB4eeOE4zuu9OnfEEp2c037f%0AFEVnAjqnUuZSkRtPCSLkW8kTfei7cv6ymvYNmeY0ciaj%2Fr3V76UWpOkf9z8gmEPJrM%2BAaxMr5l3v%0A7oIAWcXMNXB2xyrv7xXB%2BZMdPUKlkd6YhFk72UsT13efuF%2FbWjf76AelE5SOGXFeAxSeCi8N2Hb1%0Ag8ohwRfH83p5Ap1YSk47wRQYAVzWIo3qCEipDOa7%2FQ0W9qWL8ySACr6M9y2DtuXy7iIvM0HHLS%2BD%0A72ehIFTyAA3huLTkJ6cm%2Bmick3BorzDZV%2FFl4TQ2%2BTqDGg%2BsUGP2armRPbFv%2BdPdFMTYb7%2FJ%2BLWg%0AC1e%2BtFC62GzR5RSpdR4V5RPrV7BO9gDQFMqYR8SIK2BMdMYOmR1iCM1OfLgnqnBewh18iB1HzQn%2B%0AhjCR2lSjoBY68AXiGdgExMb7MYSwUrHLzQlQHWSf3%2B0fFM2SL7BKvaDb2xZHfNLVDaCIZXLYw0tJ%0ADEJS1J25rBAEiiHqA0%2F%2BpHYMFlpFze6p2eHRlX0awaWkn1z%2F%2BA%3D%3D&ddkey=https:UserRegistrationUpdate"
		direct_url URL    
    end  
end
