#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Bonmarche
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.bonmarche.co.uk/bin/venda"
		direct_url URL    
    end  
end
