#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Bonmarche
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.bonmarche.co.uk/bin/venda?ex=co_wizr-register&bsref=shop"
      direct_url URL
      
  	  text_field(:username, :id=>"email")
      text_field(:password, :id=>"password")  
  	  button(:login_submit, :id=>"signinsubmit")           
    end  
end
