#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Bonmarche
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.bonmarche.co.uk/shop-by-product/skirts/icat/skirts/"
      direct_url URL      

    end  
end
