#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Brora
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.brora.co.uk/Basket/Basket.aspx"
      direct_url URL
      
      link(:basket_checkout, :id => "ctl00_BrowseContentPlaceHolder_CheckOutImageButton")
      
       
      
      def remove_product_links
        button_elements(:class => "ctl00_BrowseContentPlaceHolder_BasketGridView_ctl02_RemoveImageButton")
      end 
      
    end  
end
