#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Burton
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.burton.co.uk/en/bruk/category/clothing-281559/mens-jeans-281570"
      direct_url URL      

    end  
end
