#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Burtoneu
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://eu.burton-menswear.com/en/breu/product/clothing-1676695/mens-knitwear-2280166/tobacco-patch-pocket-cardigan-2317337?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
