#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Burtoneu
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://eu.burton-menswear.com/webapp/wcs/stores/servlet/LogonForm?catalogId=35119&storeId=13091&krypto=PiDQeD3mOY3gt4w79DeCfEyRu762uxeiqljJTI1g%2Fzpi9eeR8r5Os9T7B6LqbfjteIr6Et9QiKCq%0AKwXloyNSmQ%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
