#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Burton
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.burton.co.uk/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-1&storeId=12551&catalogId=33052&beginIndex=1&viewAllFlag=false&pageSize=20&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dvd&x=0&y=0"
      direct_url URL            
    end  
end
