#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Cathkidston
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.cathkidston.co.uk/signin.aspx"
      direct_url URL
      
  	  text_field(:username, :id=>"EMail")
      text_field(:password, :id=>"txtPassword")  
  	  button(:login_submit, :name=>"existingLoginButton")           
    end  
end
