#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Cathkidston
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.cathkidston.co.uk/shoppingcart.aspx"
      direct_url URL
      
      button(:basket_checkout, :id => "btnCheckOutNowBottom")
      
       
      
      def remove_product_links
        button_elements(:class => "CartDeleteButton")
      end 
      
    end  
end
