#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Ccfashion
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.ccfashion.co.uk/pws/secure/ManageAccount.ice?secure_from=login"
      direct_url URL
      
  	  text_field(:username, :id=>"j_username")
      text_field(:password, :id=>"j_password")  
  	  button(:login_submit, :class=>"submit")           
    end  
end
