#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Ccfashion
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.ccfashion.co.uk/fcp/product/countrycasuals/Dresses/Clematis-Posy-Burnout-Dress/6875"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :id=> "addToBagBtn")
       
      # page elements
      
      button(:add_to_basket, :id=> "addToBagBtn")
      
    end  
end
