#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Chemistdirect
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.chemistdirect.co.uk/shopping_cart.php"
      direct_url URL
      
      button(:basket_checkout, :class => "continue_shop_button")
      
       
      
      def remove_product_links
        image_elements(:src => "images/basket_delete.png")
      end 
      
    end  
end
