#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Chemistdirect
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.chemistdirect.co.uk/salcura-antiac-skin-therapy-spray_1_177583.html"
      direct_url URL
	  # site elements
       
      # page elements
      
      link(:add_to_basket, :class => "buy_now")
      
    end  
end
