#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Cooksongold
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.cooksongold.com/Solders/9ct-Yellow-Gold-Solder-Panels------Easy-Assay-Quality-.375-prcode-PEB-000"
      direct_url URL
	  # site elements
       
      # page elements
      
      link(:add_to_basket, :link_text => "Add to Basket")
      
    end  
end
