#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Cooksongold
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.cooksongold.com/your_order.jsp"
		direct_url URL    
    end  
end
