#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Cottontraders
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.cottontraders.co.uk/search?q=shirt&searchsubmit=Search&categories=shop"
      direct_url URL            
    end  
end
