#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Ctshirts
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.ctshirts.co.uk/mens-shirts/mens-formal-shirts?q=gbpdefault|||||||||||||||"
      direct_url URL      

    end  
end
