#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Ctshirts
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.ctshirts.co.uk/SearchNoResults.aspx?term=shirts"
      direct_url URL            
    end  
end
