#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dawsons
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.dawsons.co.uk/catalogsearch/result/?q=black+guitar"
      direct_url URL            
    end  
end
