#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Demostore
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://showcase.peerius.com/index.php/checkout/cart/"
      direct_url URL
      
       
      
    end  
end
