#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Demostoredev
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "http://showcase-dev.peerius.com/index.php/checkout/onepage/"
		direct_url URL    
    end  
end
