#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dmaxde
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.dmax-shop.de/zuhause/essen-und-trinken/"
      direct_url URL      

    end  
end
