#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dmaxde
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.dmax-shop.de/thumbsup-schluesselfinder-whistle-688.html"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :id => "basketButton")
       
      # page elements
      
      button(:add_to_basket, :id=> "basketButton")
      
    end  
end
