#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dmaxde
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.dmax-shop.de/checkout/cart"
      direct_url URL
      
       
      
    end  
end
