#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkinsid
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://id.dorothyperkins.com/en/dpid/product/clothing-1630398/dresses-1630619/petite-lace-fit-and-flare-dress-2096748?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
