#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkinsth
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://th.dorothyperkins.com/en/dpth/product/clothing-1584002/dresses-1584223/petite-diamante-2in1-dress-2132864?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
