#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkinseu
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://euro.dorothyperkins.com/en/dpeu/category/clothing-742124/dresses-742148"
      direct_url URL      

    end  
end
