#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkinsfr
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.dorothyperkins.fr/fr/dpfr/produit/chaussures-695633/chaussures-talons-695684/chaussures-compens%C3%A9es-noires-dp-occasion-2315427?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
