#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkinsid
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://id.dorothyperkins.com/en/dpid/category/clothing-1630398/dresses-1630619"
      direct_url URL      

    end  
end
