#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkinssg
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://sg.dorothyperkins.com/webapp/wcs/stores/servlet/LogonForm?catalogId=34597&storeId=13079&krypto=E6DYHeNPFBHY5HQrFNA0paZoyKrgBbFMSzSVVEaLuZlwbZ6mxr%2F26qE%2F%2Fi4aUM5FGV0yKrDLCEg6%0AgDsHBCwc6Q%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
