#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkinsth
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://th.dorothyperkins.com/webapp/wcs/stores/servlet/LogonForm?catalogId=35099&storeId=13081&krypto=sL1GNT%2FvNwWYptit8eRIMo2rthXETZZlHvfvrAXs0hP%2FibeBV8saCezmrRkOGCQ1gzotxk%2F07QzE%0A5c5bvHkUSA%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
