#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkinsmy
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://my.dorothyperkins.com/webapp/wcs/stores/servlet/LogonForm?catalogId=35097&storeId=13080&krypto=9d74qHMm0JJNFt%2BPnF8Zqvp7eXxSkQ0yjWoVU2%2Fajis%2BkzLIwLzd4kkFXA4%2BmgmX60EG%2FBg7MjQQ%0AOapwkXEpzw%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
