#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkinsfr
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.dorothyperkins.fr/webapp/wcs/stores/servlet/LogonForm?catalogId=34068&storeId=13063&krypto=tLES0XsXm%2F1gRTd22105blzlujkAuyCDmp4dTggdXygPetY77LWxQSYer%2FgQSDVj9Jpt6ylSJTIH%0AG8d%2BvHS3Hw%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
