#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkinsth
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://th.dorothyperkins.com/en/dpth/category/clothing-1584002/dresses-1584223"
      direct_url URL      

    end  
end
