#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkinsus
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://us.dorothyperkins.com/en/dpus/category/clothing-788621/dresses-788645"
      direct_url URL      

    end  
end
