#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkinsfr
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.dorothyperkins.fr/fr/dpfr/cat%C3%A9gorie/v%C3%AAtements-695630/robes-695654"
      direct_url URL      

    end  
end
