#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Dorothyperkins
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.dorothyperkins.com/en/dpuk/category/shoes-203538/sandals-203629"
      direct_url URL      

    end  
end
