#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Evanseu
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://euro.evansfashion.com/en/eveu/category/clothing-927595/dresses-927625"
      direct_url URL      

    end  
end
