#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Evanseu
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://euro.evansfashion.com/webapp/wcs/stores/servlet/OrderItemDisplay?catalogId=34084&langId=-1&storeId=13071"
      direct_url URL
      
      link(:basket_checkout, :id => "checkout_submit_bottom")
      
       
      
      def remove_product_links
        link_elements(:class => "remove_bag_item")
      end 
      
    end  
end
