#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Evans
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.evans.co.uk/en/evuk/category/clothing-250468/dresses-250498"
      direct_url URL      

    end  
end
