#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Evansde
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.evansmode.de/webapp/wcs/stores/servlet/LogonForm?catalogId=34082&storeId=13070&krypto=Em4krnn4SpDFAAeZN5seIB7fYO10jgpP5TgdKkiCMYqXBVhY2Y6aWzw%2Bdj8NKSl4NrRrMsyf6sjL%0AOGC3p644Vw%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
