#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Evansde
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.evansmode.de/de/evde/kategorie/kleidung-912294/tops-tuniken-2105037"
      direct_url URL      

    end  
end
