#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Frenchconnectionus
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://usa.frenchconnection.com/product/man+collections+accessories/SV109/Eau+de+fcuk+115ml.htm"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :id=> "addToBasket")
       
      # page elements
      
      button(:add_to_basket, :id => "addToBasket")
      
    end  
end
