#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Frenchconnectionus
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://usa.frenchconnection.com/checkout.htm"
		direct_url URL    
    end  
end
