#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Greatplains
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.greatplains.co.uk/category/womens+Accessories/Accessories.htm"
      direct_url URL      

    end  
end
