#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Isabellaoliver
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.isabellaoliver.com/uk/cart"
      direct_url URL
      
      span(:basket_checkout, :text => "Secure Checkout")
      
       
      
      def remove_product_links
        button_elements(:class => "remove link")
      end 
      
    end  
end
