#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Isabellaoliver
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.isabellaoliver.com/maternity-clothes/uk/member-login.html"
      direct_url URL
      
  	  text_field(:username, :id => "loginemail")
      text_field(:password, :id => "loginpass")  
  	  button(:login_submit, :class => "btn-med login")           
    end  
end
