#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Jaeger
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.jaeger.co.uk/on/demandware.store/Sites-JGRUK-Site/en_GB/Cart-Show"
      direct_url URL
      
      link(:basket_checkout, :class => "abtnSecurechkout")
      
       
      
      def remove_product_links
        button_elements(:class => "textbutton remove-btn")
      end 
      
    end  
end
