#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Jaeger
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.jaeger.co.uk/on/demandware.store/Sites-JGRUK-Site/en_GB/Search-Show?q=coats"
      direct_url URL            
    end  
end
