#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Jakoo
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.jako-o.com/products-kids-fashion-boy-s-fashion-size-92-158-jeans-and-trousers-straight-cut-trousers--753485.html"
      direct_url URL
	  # site elements
       
      # page elements
      
      span(:add_to_basket, :class=> "jsOnClickBasket")
      
    end  
end
