#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Jakoo
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.jako-o.com/warenkorb/anzeige"
      direct_url URL
      
      link(:basket_checkout, :text => "Proceed to Checkout")
      
       
      
      def remove_product_links
        link_elements(:text => "Remove Item")
      end 
      
    end  
end
