#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Jakoo
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.dmax-shop.de/SwpFindologic/search?sSearch=machette"
      direct_url URL            
    end  
end
