#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Jojomamanbebe
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.jojomamanbebe.co.uk/docontents.asp"
      direct_url URL
      
      link(:basket_checkout, :id => "checkoutBtn")
      
       
      
      def remove_product_links
        link_elements(:xpath => "/html/body/div/div/div[6]/div[2]/div/form/div[5]/table[3]/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr/td/a[2]")
      end 
      
    end  
end
