#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Kickzde
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.kickz.com/de/catalog/fullTextSearch?queryString=nike&search=suche"
      direct_url URL            
    end  
end
