#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Lensspirit
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.lensspirit.de/Produkt/10522/SofLens-Daily-Disposable-lenses-90-per-box-/cross-selling_recommend-best-B/"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :value => "Add to shopping cart")
      
    end  
end
