#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Lensspirit
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.lensspirit.de/search/"
      direct_url URL            
    end  
end
