#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Lovehoney
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.lovehoney.co.uk/lingerie/sexy-costumes/"
      direct_url URL      

    end  
end
