#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Lovehoney
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://search.lovehoney.co.uk/search?w=toy&p=Q&asug=&view=grid"
      direct_url URL            
    end  
end
