#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Microscootersuk
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.micro-scooters.co.uk/category/aluminium-scooters-5-to-adult/"
      direct_url URL      

    end  
end
