#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Missselfridgefr
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.missselfridge.fr/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-2&storeId=13067&catalogId=34076&beginIndex=1&viewAllFlag=false&pageSize=40&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dress&x=0&y=0"
      direct_url URL            
    end  
end
