#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Missselfridgede
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.missselfridge.de/webapp/wcs/stores/servlet/OrderItemDisplay?catalogId=34074&langId=-3&storeId=13066"
      direct_url URL
      
      link(:basket_checkout, :text=> "Zur Kasse")
      
       
      
      def remove_product_links
        link_elements(:class => "remove_bag_item")
      end 
      
    end  
end
