#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Missselfridgeeu
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://euro.missselfridge.com/en/mseu/category/clothing-873726/dresses-873739"
      direct_url URL      

    end  
end
