#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Missselfridgefr
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.missselfridge.com/webapp/wcs/stores/servlet/UserRegistrationForm?langId=-2&catalogId=34076&storeId=13067&krypto=1bAVQTQIol7vHBQsMn8ZZRccjGmFEGKxdiQ%2B%2FDjZiIePa63p9ooyNO4HOCb6ZNW6Wpunm4WsTB1m%0A4HzTy1KnSyr%2FbhYofTF05nhtcs%2FgJLazrSKmoNzPZ9GgR6CzCUiz81vJuwYFoaceJgqyGAU1yN6i%0AasenXXQL&ddkey=https:PreCheckout"
		direct_url URL    
    end  
end
