#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Missselfridgeus
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://us.missselfridge.com/en/msus/category/apparel-893014/dresses-893027"
      direct_url URL      

    end  
end
