#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Notonthehighstreet
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.notonthehighstreet.com/session/new"
      direct_url URL
      
  	  text_field(:username, :id=>"session_email")
      text_field(:password, :id=>"session_password")  
  	  button(:login_submit, :value=>"sign in")           
    end  
end
