#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Notonthehighstreet
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.notonthehighstreet.com/cooperrowevintageliving/product/reclaimed-oak-bench"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :id=> "add_to_cart")
       
      # page elements
      
      button(:add_to_basket, :id=> "add_to_cart")
      
    end  
end
