#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Predatornutrition
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.predatornutrition.com/en/catalogsearch/result/?q=chocolate"
      direct_url URL            
    end  
end
