#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Redletterdays
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.redletterdays.co.uk/SearchNoResults.aspx?term=abc"
      direct_url URL            
    end  
end
