#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Royalmint
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.royalmint.com/our-coins/events/the-glasgow-2014-commonwealth-games"
      direct_url URL      

    end  
end
