#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Schuh
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.schuh.co.uk/search"
      direct_url URL            
    end  
end
