#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Simplypersonalized
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.simplypersonalized.com/Checkout.aspx"
		direct_url URL    
    end  
end
