#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Sinnleffers
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.sinnleffers.de/Herren/Accessoires/Schals/"
      direct_url URL      

    end  
end
