#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Sinnleffers
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.sinnleffers.de/Looks-Trends/Trendthemen/Stricktrend-Herren/Schal-im-Burberry-Stil-schwarz-FRAAS.html"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :value => "in den Warenkorb")
      
    end  
end
