#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdrycacaen
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdrystore.ca/ca-en/search/jacket"
      direct_url URL            
    end  
end
