#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdrynl
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.nl/dames/chinos/details/39116/commodity-capribroek"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :src=> "http://www.superdry.nl/public/images/languages/nl-NL/product/add-to-bag.png")
      
    end  
end
