#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdrycacaen
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdrystore.ca/ca-en/womens/chinos/details/39116/commodity-capri-pant"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :src=> "http://www.superdrystore.ca/ca-en/public/images/languages/en-GB/product/add-to-bag.png")
      
    end  
end
