#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdry
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.com/womens/dresses/details/43255/hepburn-lights-dress"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :value => "Add to bag")
       
      # page elements
      
      button(:add_to_basket, :value => "Add to bag")
      
    end  
end
