#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdryfi
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.fi/naiset/chinot/details/39121/commodity-capri--housut"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :src=> "http://www.superdry.fi/public/images/languages/fi-FI/product/add-to-bag.png")
      
    end  
end
