#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdryfi
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.fi/naiset/chinot"
      direct_url URL      

    end  
end
