#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdryno
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.superdrystore.no/checkout"
		direct_url URL    
    end  
end
