#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdryde
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.de/damen/stiefel/details/37514/schuh-eva"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :src=> "http://www.superdry.de/public/images/languages/de-DE/product/add-to-bag.png")
      
    end  
end
