#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdrycacaen
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdrystore.ca/ca-en/womens/chinos"
      direct_url URL      

    end  
end
