#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdrycacafr
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdrystore.ca/ca-fr/femme/chinos/details/39116/pantacourt-commodity"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :src=> "http://www.superdrystore.ca/ca-fr/public/images/languages/fr-FR/product/add-to-bag.png")
      
    end  
end
