#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdrug
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.thewhitecompany.com/search/towel/"
      direct_url URL            
    end  
end
