#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdrychchfr
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.superdrystore.ch/ch-fr/checkout"
		direct_url URL    
    end  
end
