#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdryes
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.es/mujer/chinos/details/39116/pantalones-commodity-capri"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :src=> "http://www.superdry.es/public/images/languages/es-ES/product/add-to-bag.png")
      
    end  
end
