#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdryno
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdrystore.no/dame/chinos/details/39116/commodity-capribukser"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :src=> "http://www.superdrystore.no/public/images/languages/nb-NO/product/add-to-bag.png")
      
    end  
end
