#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdryde
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.superdry.de/herren/lederjacken"
      direct_url URL      

    end  
end
