#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdry
  
    class HomePage
		include PageObject
		include PeeriusHelper

		URL = "http://www.superdry.com/"
		direct_url URL
		#page elements - retained for backward compatibility
		
		text_field(:search_field, :name => "searchword")
        
		
		link(:login_link, :href => "http://www.superdry.com/my-account")
		
        # site elements
		
		 
		
		div(:category_menu, :class => "main-menu")
		
		
		
		ul(:product_links, :class => "grid4")
		
		
		button(:add_to_basket, :value => "Add to bag")
      	 
      	
      	
		ul(:product_option1, :xpath=> "//div[@id=\"js_dropdown_product_id\"]/ul")
		
	    
	    
		
		span(:product_options_preselect1, :xpath=> "//div[@id=\"js_dropdown_product_id\"]/span[1]")
		

		# methods
		def get_product_link_filter
				
			return ["rel", "product"]
				
		end
		
		def get_product_option_filter
		
			return []
				
		end
		
		def get_max_num_of_categories
		
			return 1
		
		end 

		def get_max_num_of_products
		
			return 1
		
		end 
		
		def get_num_of_reloads_per_category
		
			return 5
		
		end 
		
		def get_wait_time_per_category_page
		
			return 3
		
		end 
		
		def get_categories_to_exclude
				
			return ["menuitem9999"]
				
		end
		
		def get_category_paging_info
		
			return []
		
		end
	
		def get_wait_time_per_product_page
		
			return 5
		
		end
		
		def get_num_of_product_options
				
			return 1
				
		end
		
		def get_product_keywords_to_exclude
		
			return []
				
		end
		
		def get_out_of_stock_msg
		
			return nil
				
		end
		
		def has_product_options_preselect
				
			return true
				
		end
		
		def show_log
		
			return true
		
		end 
		
		def ignore_cat_tracked_as_other_page
		
			return true
		
		end 
		
		def get_add_to_basket_error_msg
		
			return nil
			
		end
		
		
		def is_static_test_enabled
		
			return false
		
		end 
		
		def get_static_test_cat_url
		
			return ""
		
		end
		
		def get_static_test_prod_url
		
			return nil
		
		end 
		
		def get_custom_search_js
		
			return nil
		
		end 
		
		def has_search_button
		
			return false
				
		end
		
		def get_ab_group
		
			return nil
		
		end 
		
		
    end  
end
