#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Superdrybebenl
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.superdry.be/be-nl/checkout"
		direct_url URL    
    end  
end
