#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Tedbaker
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.tedbaker.com/uk/Womens/Accessories/Bags/LUCON-Small-shopper-bag-Bright-Pink/p/108369-56-BRIGHT-PINK"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :class=> "button add_to_cart major full_mobile colour_dark")
       
      # page elements
      
      button(:add_to_basket, :class=> "button add_to_cart major full_mobile colour_dark")
      
    end  
end
