#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Thewhitecompany
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.thewhitecompany.com/candles-and-fragrance/accessories/ceramic-bottle-arch--white/"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :id=> "btnAddtoBasketTop")
       
      # page elements
      
      button(:add_to_basket, :id=> "btnAddtoBasketTop")
      
    end  
end
