#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Toast
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.toast.co.uk/basket.htm"
      direct_url URL
      
      link(:basket_checkout, :id=>"ctl00_globalMainContent_hlCheckout")
      
       
      
      def remove_product_links
        image_elements(:src=>"//d1kh76s6bjh8ww.cloudfront.net/img/Close_60px.png")
      end 
      
    end  
end
