#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Tommyhilfigereu
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://eu.tommy.com/on/demandware.store/Sites-EU-Site/default/Account-Show"
      direct_url URL
      
  	  text_field(:username, :id => "dwfrm_login_username")
      text_field(:password, :id => "dwfrm_login_password")  
  	  button(:login_submit, :name => "dwfrm_login_customlogin")           
    end  
end
