#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Tommyhilfigernl
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://nl.tommy.com/Polo%27s/206000,nl_NL,sc.html"
      direct_url URL      

    end  
end
