#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Tommyhilfigerchfr
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://ch.tommy.com/Polos/106000,fr_CH,sc.html"
      direct_url URL      

    end  
end
