#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Tommyhilfigereu
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://eu.tommy.com/Polos/106000,default,sc.html"
      direct_url URL      

    end  
end
