#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Tommyhilfigerchfr
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://ch.tommy.com/on/demandware.store/Sites-CH-Site/fr_CH/Search-Show?q=shirt"
      direct_url URL            
    end  
end
