#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Tommyhilfigerfr
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://fr.tommy.com/Polos/206000,fr_FR,sc.html"
      direct_url URL      

    end  
end
