#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Tommyhilfigerbenl
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://fr.tommy.com/on/demandware.store/Sites-FR-Site/fr_FR/Search-Show?q=shirt"
      direct_url URL            
    end  
end
