#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Tommyhilfigeres
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = ""
		direct_url URL    
    end  
end
