#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Tommyhilfigernl
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://nl.tommy.com/on/demandware.store/Sites-NL-Site/nl_NL/Search-Show?q=shirt"
      direct_url URL            
    end  
end
