#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Tommyhilfigerde
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://de.tommy.com/Polos/106000,de_DE,sc.html"
      direct_url URL      

    end  
end
