#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Tommyhilfigeres
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://es.tommy.com/Camisas/203000,es_ES,sc.html"
      direct_url URL      

    end  
end
