#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topmanid
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://id.topman.com/en/tmid/category/clothing-1459570/mens-jeans-1459636"
      direct_url URL      

    end  
end
