#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topmande
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://de.topman.com/webapp/wcs/stores/servlet/LogonForm?catalogId=34060&storeId=13059&krypto=ogeJmQm6IxISFTo%2FL7%2FgOYtCVe7kG1a9eCDb9yXfbwPSAcUYtSYESwnGKtHatauZ6FCGTlOAymtO%0AdVqnw7IXvw%3D%3D&ddkey=http:CatalogNavigationSearchResultCmd"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
