#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topman
  
    class HomePage
		include PageObject
		include PeeriusHelper

		URL = "http://www.topman.com/"
		direct_url URL
		#page elements - retained for backward compatibility
		
		text_field(:search_field, :id => "inp_search_text")
        
		
		link(:login_link, :title => "My Account")
		
        # site elements
		
		 
		
		ul(:category_menu, :id => "nav_catalog_menu")
		
		
		
		div(:product_links, :id=> "wrapper_page_content")
		
		
		button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      	 
      	
      	
		select_list(:product_option1, :id=> "product_size_full")
		
	    
	    
		
		select_list(:product_options_preselect1, :id=> "product_size_full")
		

		# methods
		def get_product_link_filter
				
			return ["data-productid", "*"]
				
		end
		
		def get_product_option_filter
		
			return []
				
		end
		
		def get_max_num_of_categories
		
			return 1
		
		end 

		def get_max_num_of_products
		
			return 1
		
		end 
		
		def get_num_of_reloads_per_category
		
			return 2
		
		end 
		
		def get_wait_time_per_category_page
		
			return 3
		
		end 
		
		def get_categories_to_exclude
				
			return ["Topman Magazine", "Brands", "Offers", "Sale", "Inspire Me", "Topshop"]
				
		end
		
		def get_category_paging_info
		
			return []
		
		end
	
		def get_wait_time_per_product_page
		
			return 2
		
		end
		
		def get_num_of_product_options
				
			return 1
				
		end
		
		def get_product_keywords_to_exclude
				
			return ["Suit"]
				
		end
		
		def get_out_of_stock_msg
		
			return nil
				
		end
		
		def has_product_options_preselect
				
			return true
				
		end
		
		def show_log
		
			return true
		
		end 
		
		def ignore_cat_tracked_as_other_page
		
			return true
		
		end 
		
		def get_add_to_basket_error_msg
		
			return nil
			
		end
		
		
		def is_static_test_enabled
		
			return false
		
		end 
		
		def get_static_test_cat_url
		
			return ""
		
		end
		
		def get_static_test_prod_url
		
			return nil
		
		end 
		
		def get_custom_search_js
		
			return nil
		
		end 
		
		def has_search_button
		
			return false
				
		end
		
		def get_ab_group
		
			return nil
		
		end 
		
		
    end  
end
