#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topmansandpit
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://tm.sandpit.arcadiagroup.ltd.uk/webapp/wcs/stores/servlet/LogonForm?catalogId=33056&storeId=12555&krypto=uv4XFNHYwVG4uTPXJsCkTA%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
