#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topmansandpit
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://tm.sandpit.arcadiagroup.ltd.uk/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?catalogId=33056&storeId=12555&langId=-1&viewAllFlag=false&sort_field=Relevance&categoryId=207185&parent_categoryId=207169&beginIndex=1&pageSize=20"
      direct_url URL      

    end  
end
