#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topmanmy
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://my.topman.com/en/tmmy/product/shoes-and-accessories-1928532/casual-shoes-1396826/house-of-hounds-navy-suede-tassle-slippers-2124040?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
