#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topmanus
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://us.topman.com/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-1&storeId=13051&catalogId=33059&beginIndex=1&viewAllFlag=false&pageSize=20&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dvd&x=0&y=0&geoip=noship"
      direct_url URL            
    end  
end
