#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topmande
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://de.topman.com/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-3&storeId=13059&catalogId=34060&beginIndex=1&viewAllFlag=false&pageSize=20&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dvd&x=0&y=0"
      direct_url URL            
    end  
end
