#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topshopde
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://de.topshop.com/de/tsde/kategorie/bekleidung-345341/kleider-345356"
      direct_url URL      

    end  
end
