#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topshopfr
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://fr.topshop.com/fr/tsfr/cat%C3%A9gorie/v%C3%AAtements-415222/robes-415237"
      direct_url URL      

    end  
end
