#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topshopth
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://th.topshop.com/en/tsth/product/clothing-1226642/dresses-1226782/fluro-embroided-pencil-dress-2023395?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
