#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topshopsg
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://sg.topshop.com/webapp/wcs/stores/servlet/LogonForm?catalogId=35111&storeId=13087&krypto=H9vzPnmwDMsV2nIYdfl9fyDUEhmTXPjxQQJqbluN1ZU5oBPRqG%2BUZKFimvZWNKWsHhzsjdaaSQZa%0A58s8FF1Qaw%3D%3D&ddkey=http:en/bhuk/category/women-1020590/new-in-1020636/tops-t-shirts-1020658"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
