#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topshopsg
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://sg.topshop.com/en/tssg/product/clothing-1087626/dresses-1087766/limited-edition-halter-neck-origami-dress-2142984?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
