#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topshop
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.topshop.com/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?catalogId=33057&storeId=12556&langId=-1&viewAllFlag=false&sort_field=Relevance&categoryId=208524&parent_categoryId=203984&beginIndex=1&pageSize=20"
      direct_url URL      

    end  
end
