#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topshopth
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://th.topshop.com/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-1&storeId=13089&catalogId=35115&beginIndex=1&viewAllFlag=false&pageSize=20&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=abcd&x=0&y=0"
      direct_url URL            
    end  
end
