#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topshopde
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://de.topshop.com/de/tsde/produkt/bekleidung-345341/kleider-345356/besticktes-ballkleid-1980027?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
