#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topshopeu
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://eu.topshop.com/webapp/wcs/stores/servlet/LogonForm?catalogId=34058&storeId=13058&krypto=ZmXU4%2F298ZR5E%2F0A%2BRepeYwmdebl9zQSPBD8LHbBD%2BmuZ5pEGZo88KNp9F2YJhO8CEqkzHXu08s9%0ANonYFRXhUg%3D%3D&ddkey=http:CatalogNavigationSearchResultCmd"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
