#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Topshopus
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://us.topshop.com/webapp/wcs/stores/servlet/OrderItemDisplay?catalogId=33060&langId=-1&storeId=13052"
      direct_url URL
      
      link(:basket_checkout, :class => "btn_checkout")
      
       
      
      def remove_product_links
        link_elements(:class => "remove_bag_item")
      end 
      
    end  
end
