#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Wallisus
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wallisfashion.com/en/wlus/category/clothing-1004840/dresses-1004858"
      direct_url URL      

    end  
end
