#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Wallisde
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wallismode.de/de/wlde/kategorie/bekleidung-958225/kleider-958243"
      direct_url URL      

    end  
end
