#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Wallisfr
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wallismode.fr/fr/wlfr/produit/accessoires-973770/sacs-sacs-%C3%A0-main-973841/sac-bandouli%C3%A8re-fauve-fiorelli-2069927?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
