#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Wallisfr
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.wallismode.fr/webapp/wcs/stores/servlet/LogonForm?catalogId=34090&storeId=13074&krypto=NLCd6qnZviHaAlzlJ%2FPSnhRGFA3Xc%2FpjVhAKOMtoQVkQnQymTyeVftKzkvsZVA62Q6WsR2KXbe3t%0Agu9qwtlY4w%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
