#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Walliseu
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://euro.wallisfashion.com/en/wleu/category/clothing-989288/dresses-989306"
      direct_url URL      

    end  
end
