#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Wallisde
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.wallismode.de/webapp/wcs/stores/servlet/LogonForm?catalogId=34088&storeId=13073&krypto=FkjzkJmK7YLzf5DrSyFsqMYrgIZKRDjGIKMkpSMj1AVYp5xDra3yPnuVvusZXyQMTdrtPbVSAtLW%0AA7kiMyOMEg%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
