#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Wolfordus
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wolfordshop.com/Accessories/cp56538/cl1/vt01/"
      direct_url URL      

    end  
end
