#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Wolfordus
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.wolfordshop.com/vm/AddOrder/?omni_scView=scView"
      direct_url URL
      
      a(:basket_checkout, :class => "continue-shipto-button button")
      
       
      
      def remove_product_links
        button_elements(:class => "checkout-delete-item")
      end 
      
    end  
end
