#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Wolfordus
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.wolfordshop.com/Accessories/Bra-Straps-Naked/cp56538/si4471101/cl2/vt01/"
      direct_url URL
	  # site elements
       
      # page elements
      
      a(:add_to_basket, :id => "add-to-cart-button-id")
      
    end  
end
