#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Zoogigant
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.zoogigant.de/Vogel/Vogelfutter-Zusatz/-0-1325/Vitakraft-Fruchtcocktail-fuer-Sittiche.html"
      direct_url URL
	  # site elements
      
      link(:add_to_basket, :id=> "cart_button")
       
      # page elements
      
      link(:add_to_basket, :id=> "cart_button")
      
    end  
end
