#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v2.0.20140717
#

module Zoogigant
  
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.zoogigant.de/shopping_cart.php"
      direct_url URL
      
      link(:basket_checkout, :id => "checkout_button")
      
       
      
      def remove_product_links
        link_elements(:id => "button_cart_delete")
      end 
      
    end  
end
