<% if site["ignore"] or site["apikey"].nil? %>
#ignore
<% end %>
#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %>
#
@<%= site["site_name"] %>
@smartapi


Feature: <%= site["pretty_name"] %> SMART-API tracking

Background:
    Given I am using SMART-API to access <%= site["site_name"] %>
<% if site["uat_apikey"] %>
    And I am using uat client token <%= site["uat_apikey"] %>
    And I am using production client token <%= site["apikey"] %>
<% else %>
    And I am using client token <%= site["apikey"] %>
<% end %>

Scenario Outline: <%= site["pretty_name"] %> Homepage is tracked using SMART-API
    When I track a home page
    Then I should get an OK status back
    Examples:
    | version |
    | v1      |
    | v1_1    |
	| v1_2    |

Scenario Outline: Product page is tracked using SMART-API
    When I track a product page
    Then I should get an OK status back
    Examples:
    | version |
    | v1      |
    | v1_1    |
	| v1_2    |

Scenario Outline: Category page is tracked using SMART-API v1
    When I track a category page
    Then I should get an OK status back
    Examples:
    | version |
    | v1      |
    | v1_1    |

Scenario Outline: Basket page is tracked using SMART-API v1
    When I track a basket page
    Then I should get an OK status back
    Examples:
    | version |
    | v1      |
    | v1_1    |
	| v1_2    |

Scenario Outline: Checkout page is tracked using SMART-API v1
    When I track a checkout page
    Then I should get an OK status back
    Examples:
    | version |
    | v1      |
    | v1_1    |
	| v1_2    |

Scenario: Order page is tracked using SMART-API v1.1
    When I track an order page
    Then I should get an OK status back

Scenario: Search results page is tracked using SMART-API v1.1
    When I track a search results page
    Then I should get an OK status back