<% if site["ignore"] or site["apikey"].nil? %>
#ignore
<% end %>
#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v<%= QA_GENERATE_VERSION %>
#
@<%= site["site_name"] %>
@smartapi

Feature: <%= site["pretty_name"] %> SMART-API content

Background:
    Given I am using SMART-API to access <%= site["site_name"] %>
<% if site["uat_apikey"] %>
    And I am using uat client token <%= site["uat_apikey"] %>
    And I am using production client token <%= site["apikey"] %>
<% else %>
    And I am using client token <%= site["apikey"] %>
<% end %>

<% for page_name in ["home", "category", "product", "basket", "checkout", "order", "searchresults", "brand", "attribute", "other"] %>
<% page = site[page_name+"_page"] %>
<% if page && page["expected_api_content"] %>
Scenario: <%= site["pretty_name"] %> SMART-content can be delivered on <%= page_name %> page using SMART-API
    When I track the <%= page_name %> page        
    Then I should get an OK status back
    And I should get at least <%= page["expected_api_content"] %> SMART-content creatives in the response        

Scenario: <%= site["pretty_name"] %> SMART-content clicks can be tracked on <%= page_name %> page using SMART-API
   
    When I track the <%= page_name %> page
    And I track a click for the first SMART-content creative
    Then I should get an OK status back
<% end %>
<% end %>