#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Lensspirit
  
    class CheckoutPage
		include PageObject
		include PeeriusHelper

		URL = "https://www.lensspirit.de/checkout/"
		direct_url URL    
    end  
end
