#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Bhssandpit
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.bhs.co.uk/en/bhuk/product/women-1020590/dresses-1020593/grey-herringbonelace-dress-2263607?bi=1&ps=40"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
