#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Bhssandpit
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.bhs.co.uk/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?catalogId=34096&storeId=13077&langId=-1&viewAllFlag=false&sort_field=Relevance&categoryId=471259&parent_categoryId=471112&beginIndex=1&pageSize=40"
      direct_url URL      

    end  
end
