#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Ctshirts
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.ctshirts.co.uk/men%27s-accessories/men%27s-cufflinks/Navy-fleur-de-lys-motif-enamel-cufflinks?q=peerius||LE370NAV|||||||||||||"
      direct_url URL
	  # site elements
      
      button(:add_to_basket, :value=> "Add to basket")
       
      # page elements
      
      button(:add_to_basket, :id=> "ctl00_contentBody_ctl02_submit")
      
    end  
end
