#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4
#

module Ctshirts
    class CheckoutPage
      include PageObject
      include PeeriusHelper
      
      URL = ""
      direct_url URL            
    end  
end