#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4 on 2013-02-02 21:24:37 +0000
#

module Ctshirts
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.ctshirts.co.uk/SearchNoResults.aspx?term=abc"
      direct_url URL            
    end  
end