#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Ctshirts
  
    class HomePage
		include PageObject
		include PeeriusHelper

		URL = "http://www.ctshirts.co.uk/default.aspx?q=gbpdefault|||||||||||||||"
		direct_url URL
		
        text_field(:search, :id => "search_term")
        
		#page elements - retained for backward compatibility
		
		link(:login_link, :href=> "https://www.ctshirts.co.uk/AccountLogin.aspx")
		
        # site elements
		
		ul(:category_menu, :xpath => "//div[@id=\"menu\"]/ul")
		
		
		
		div(:product_links, :id=> "ctl00_contentBody_productListingSection")
		
		
		button(:add_to_basket, :value=> "Add to basket")
      	 
      	
      	
		ul(:product_option1, :xpath=> "html/body/div[3]/ul")
		
		dl(:product_option2, :xpath=> "html/body/div[4]/dl")
		
		ul(:product_option3, :xpath=> "html/body/div[4]/ul")
		
		ul(:product_option4, :xpath=> "html/body/ul[2]")
		
	    
	    
		
		a(:product_options_preselect1, :class=> 'tooltip_link', :index=> 0 )
		
		
		a(:product_options_preselect2, :class=> 'tooltip_link', :index=> 1 )
		
		
		a(:product_options_preselect3, :class=> 'tooltip_link', :index=> 1 )
		
		
		div(:product_options_preselect4, :class=> 'selectedTxt')
		

		# methods
		def get_product_link_filter
				
			return ["class", "img"]
				
		end
		
		def get_product_option_filter
		
			return []
				
		end
		
		def get_max_num_of_categories
		
			return 1
		
		end 

		def get_max_num_of_products
		
			return 1
		
		end 
		
		def get_num_of_reloads_per_category
		
			return 2
		
		end 
		
		def get_wait_time_per_category_page
		
			return 2
		
		end 
		
		def get_categories_to_exclude
				
			return ["Nothing"]
				
		end
		
		def get_category_paging_info
		
			return []
		
		end
	
		def get_wait_time_per_product_page
		
			return 2
		
		end
		
		def get_num_of_product_options
				
			return 4
				
		end
		
		def get_product_keywords_to_exclude
		
			return []
				
		end
		
		def get_out_of_stock_msg
				
			return "THIS PRODUCT IS SOLD OUT"
				
		end
		
		def has_product_options_preselect
				
			return true
				
		end
		
		def show_log
		
			return true
		
		end 
		
		def ignore_cat_tracked_as_other_page
		
			return true
		
		end 
		
		def get_add_to_basket_error_msg
		
			return nil
			
		end
		
		
		def is_static_test_enabled
		
			return false
		
		end 
		
		def get_static_test_cat_url
		
			return ""
		
		end
		
		def get_static_test_prod_url
		
			return nil
		
		end 
		
		def get_custom_search_js
		
			return nil
		
		end 
		
		def get_ab_group
		
			return nil
		
		end 
		
		
    end  
end
