#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4 on 2013-02-03 16:02:18 +0000
#

module Ctshirts
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.ctshirts.co.uk/Basket.aspx"
      direct_url URL
      
      link(:basket_checkout, )            
    end  
end