#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4 on 2013-02-02 21:24:37 +0000
#

module Ctshirts
    class HomePage
      include PageObject
      include PeeriusHelper
      
      URL = "www.ctshirts.com"
      direct_url URL
      
      link(:login_link, :title => "Login")            
    end  
end