#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.4
#

module Ctshirts
    class BasketPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.ctshirts.co.uk/Basket.aspx"
      direct_url URL
      
      button(:basket_checkout, :id => "ctl00_contentBody_submit")            
    end  
end