#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Tommyhilfigernl
	class ProductPage
		include PageObject
		include PeeriusHelper
		# site elements
		 
		
		# page elements
		
		button(:add_to_basket, :class=> "button active addtocartbutton a")
		



	end  
end
