#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Tommyhilfigernl
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://nl.tommy.com/Triple-Slim-Fit-Polo/0887828001,nl_NL,pd.html?cgid=206000#!color%3D370%26i%3D7"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :class=> "button active addtocartbutton a")
      
    end  
end
