#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5

#

module Boohoo
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.boohoo.com/restofworld/footwear/boots/icat/boots/"
      direct_url URL            
    end  
end