#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.5
#

module Boohoo
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.boohoo.com/restofworld/footwear/boots/icat/boots/boots/amara-nude-suedette-lace-up-perspex-block-heel-boots/invt/azz53928"
      direct_url URL
      
      button(:add_to_basket, :id=> "ctl00_contentBody_ctl02_submit")          
    end  
end