#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Bonmarche
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.bonmarche.co.uk/bags+brollies/patent-clutch-bag/invt/21561607007/&bklist=icat,5,shop,shopbyproduct,accessories,bags-and-umbrellas&bklist=icat,5,shop,shopbyproduct,accessories,bags-and-umbrellas"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :class => "add submit addproduct")
      
    end  
end
