#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Evansus
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.evansusa.com/en/evus/category/clothing-942924/dresses-942954"
      direct_url URL      

    end  
end
