#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Evansus
  
    class LoginPage
      include PageObject
      include PeeriusHelper
      
      URL = "https://www.evansusa.com/webapp/wcs/stores/servlet/LogonForm?catalogId=34086&storeId=13072&krypto=S9BNDEagYIb960r1Id1EJpxjhpXx2RJ5AW1q2nkM%2FtN1f7aJdCEUcPswmXH4DT1yGJxeLKSfVzgo%0A43J0q29xhA%3D%3D&ddkey=http:LogonForm"
      direct_url URL
      
  	  text_field(:username, :id=>"login_email")
      text_field(:password, :id=>"password")  
  	  link(:login_submit, :id=>"login_submit")           
    end  
end
