#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v0.1.8
#
@livedemoshop
@smartapi


Feature: Peerius Demo Shop SMART-API ranking -ignore for now- it's auto generated

Background:
    Given I am using SMART-API to access livedemoshop
    And I am using client token gfsdkl47gh3248

Scenario: Peerius Demo Shop SMART-ranking can be delivered on category page using SMART-API
    When I supply SMART-ranking setup info
    And I track the category page        
    Then I should get an OK status back
    And I should get at least 1 items of SMART-ranking content        

Scenario: Peerius Demo Shop SMART-ranking clicks can be tracked on category page using SMART-API
    When I supply SMART-ranking setup info
    When I track the category page
    And I track a click for the first SMART-ranking item
    Then I should get an OK status back
