#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Dmaxde
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.dmax-shop.de/SwpFindologic/search?sSearch=machette"
      direct_url URL            
    end  
end
