#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Evansde
  
    class ProductPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.evansmode.de/de/evde/produkt/kleidung-912294/kleider-912324/scarlett-jo-2-in-1-sch%C3%B6%C3%9Fchenkleid-schwarz-2318392?bi=1&ps=20"
      direct_url URL
	  # site elements
       
      # page elements
      
      button(:add_to_basket, :id=> "btn_add_2_shop_cart")
      
    end  
end
