#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140423
#

module Evansde
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://www.evansmode.de/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-3&storeId=13070&catalogId=34082&beginIndex=1&viewAllFlag=false&pageSize=20&searchTermScope=3&searchTermOperator=LIKE&searchType=ALL&sort_field=Relevance&searchTerm=dvd&x=11&y=14"
      direct_url URL            
    end  
end
