#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Tommyhilfiger
  
    class CategoryPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://uk.tommy.com/Polos/106000,en_GB,sc.html"
      direct_url URL      

    end  
end
