#
# This file is auto-generated. Please do not modify!
# Generated by QA Generator v1.0.20140224
#

module Tommyhilfiger
  
    class SearchResultsPage
      include PageObject
      include PeeriusHelper
      
      URL = "http://uk.tommy.com/on/demandware.store/Sites-GB-Site/en_GB/Search-Show?q=shirt"
      direct_url URL            
    end  
end
